[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "99b198c16d5f23edf965bd9e62a64cb42c20874b"
libgfortran_version = "5.0.0"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "8fe9a665c5e314c3f4471ff3c78a722f8b49abc88f21a2f22dd6f5e3cc8cab3c"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+1/MPItrampoline.v4.0.2.aarch64-apple-darwin-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "be68df957977c43d755d3c7494ea340a63e597e0"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "c6b60a7a6fdbb4e3c28e93e14b79d75ddb1693a87d5ab6911e0277223c8e7724"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+1/MPItrampoline.v4.0.2.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "adb9a7f2140df2417531e028e9c67af339321b4f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "a281c419769f56c0285a5ddeca96d02655f3e32b1bf42f72996fc72e142182ad"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+1/MPItrampoline.v4.0.2.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "476dd1b5e296ed4454216f6a54bdc2ccd3558aa5"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "0255852455989b475563073e77036cd06e5d5578801ab8e9a9d95625e20343d0"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+1/MPItrampoline.v4.0.2.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ea026de9f99567d2ab26b1cec59a92b843a3c72e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "bd330c931315bce2838c37f15afec1bdfb558a9aeb3156ea01325487cb2d8722"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+1/MPItrampoline.v4.0.2.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f38a4383bdc4ddc2af06815d1022af16377b331b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "3defe409a8d062a57911d8bc152f34b371cff540558c6f72b2f20106cac3d71c"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+1/MPItrampoline.v4.0.2.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f66698ff01d153f928dfa623cf1532e3442159e5"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "32fe821273e98ef6fcddb9155c8a66830eaf275eaf542c98ede460fc024bb625"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+1/MPItrampoline.v4.0.2.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "930056f89ba29f37554405867170d409763e0d55"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "9d31258446147e96033a2b268bfbc2f83fcf08e2cf43ca134dd14801980d9cf5"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+1/MPItrampoline.v4.0.2.i686-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "3a8c5da01691f77586b857b0db5fa3caee518bcb"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "31a793aa5d6350594e6e6f36bcf770a4f4e0b4cd8f9f47f540ab6910d01eedba"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+1/MPItrampoline.v4.0.2.i686-linux-gnu-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "e98b8100b5fc21654f7cfaa77ada8642b8413052"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "7ab27972366fbc61c4f26505ac4d4ede7f2af682439a56d81538356027d3a3b6"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+1/MPItrampoline.v4.0.2.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "6a1ae62be114cfe03a6dabd2964c3465ed88c330"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "d213f4a8cf25489c05e48c83b5510701b9fe5ab0ebc8b5f24545769c9a462045"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+1/MPItrampoline.v4.0.2.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "1b7c2fbc0dc69b51c86bafb42ae0f74b69925747"
libgfortran_version = "4.0.0"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "a61990865c428cc9305d43b257c22bf8d537650adcce8cb7088ec9c109e42e4b"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+1/MPItrampoline.v4.0.2.x86_64-apple-darwin-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "e1320124410999bd68f1ef08969fbbfea1a66563"
libgfortran_version = "5.0.0"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "d43c5626c38dc89ad38e510c109f71653b89a4c6938a92bb82e42bab04d9beab"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+1/MPItrampoline.v4.0.2.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "7234a5ca2b6693868de6192f7f146856a3388156"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "562c2fd8b43f0d73d7df28195c9f48c4bd8ba078735cef098347a0fcb2e033c1"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+1/MPItrampoline.v4.0.2.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "e28eb3bd73afe1ebf6cc0909ca5f24ca68e9c76e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "839d063709e3910a2dea0885740a1b43edb9ecae116173982752221fb767c99a"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+1/MPItrampoline.v4.0.2.x86_64-linux-gnu-libgfortran5.tar.gz"
