[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "4035d715f1096ca13e0e8ac30f7e1c92843a4845"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "d2bf295cb1b7345f94ee5deb42fcd51c73b2a7b847bd49634f0901868d71af00"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "3da3670564c4413d82f23894d2f1906613896392"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "66c6ab436bc7e870f9aa0cf995ef2886cac36bd0a1c20b707e2f5bff0558ac14"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.aarch64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "0db02102f62e6df8a00dc20c370ac35e716a79b3"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "8017d0ec6a292bd55b5c03f7b08eb17c61739cf311ffbf3ff7d3444f9a3c1010"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.aarch64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "0acc62ee2d22860bb58de58953072128ebe84496"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "73e3dc638f5405e62a764d83724e56389f63472b4c6dec5cbb190b418f1cfae6"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.aarch64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3b2fc9d75dbd1369dc537a038bf5c8c6e5b82867"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "76c2655dc69803b8aac92e70788e579fdd877ea8c9744c8f6c30b4f96b969ecc"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.armv6l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "87f346cc2dbe9178e80635e0d551493515e9de3c"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "734662b36724a2b2c577554e70e39a567ff32c879b0948ecef63f30e29a91dcf"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.armv6l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "671d2716d3347c61eeb9ecda1506768e84d4449e"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "2d2d5e9d08de3e986caf2dfadee6e2ae333c7a8f0bd57c6b321513f94a815394"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.armv6l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d6e28b8725fd0cc6f53ada7421711e5f462e2732"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "835d2a710b247c7bc883151bb8ceff7defe6c958c56cb9dfc1635e6104fe8be0"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.armv7l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7368cc42161338cba8d40d8c069a71eb405f7f4c"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "dde96ef0243290c47df4ef9e844c881b88dcb7fc8786e9df8d77c5525edadfa7"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.armv7l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5c622f116c49d7a60ce3535e392c888a64d0751f"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "e441dbd8f1e66fc98dbfe308b37ededdabf4115b58b731fd354bed5e226ae322"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.armv7l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "3e6c64249c6803cb024a962a241eef40542f0fca"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "b32c2c3bc75ff8cde994c7ea79165048a58de20cec970ef8bb712fb071dbee22"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.i686-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "bc84bcbc00af7e458878fb3fce0eddf5b16fd615"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "1443cb86ea6e6aa1cf1b5f10db1bae1961e4fd8a5ca41ef42305f30b9a5126a3"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.i686-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "9f3ad9f0b6ff20e6c1c77ce94f2810d8bf1e07c7"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "66ce15ed9acfcf1a060a71827209f5707aedfd62322fc013ca0429415acec387"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.i686-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "1dacd9d1af4fd559bb0ef2651f3d745501e4281e"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "e19e707ae1c29a4ef8db0e07f91a1cd54db40c0700b8a73f37de6f9511dbd41c"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.powerpc64le-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "6e3bf164b1dd7da8ce35eea4c118f060e6d6440f"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "bce450c8db6747bcac24762b36ab62d68f42a2ba3c736f47349d4bc302127b97"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.powerpc64le-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "7dc7ef251cbe81beb50cba4630959613526f0498"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "b660cf059ac729ab69cebe84716a927c5580c0f4d18b81addc69962a99c09bf6"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.powerpc64le-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "2a9e9537e8cc760ed9398ea2471d133e651e9a08"
lazy = true
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "0541c41181000c044b67871179a51465f8b8e244f43636f6d19cb7d1587b60e8"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.x86_64-apple-darwin-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "b6ef7241e909860cbaeedd374eaad4ca72daa0f9"
lazy = true
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "6a17f778b3800cb7c646a230f37ff128bf8f71a86b8f8599db603a724959f266"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.x86_64-apple-darwin-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "ddc3697c1d16e253c63d945571c8f8dec1b96a5b"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "aa4e10b82e7dfd228dc2849ca959e785fdb34b7d340353cdbb3ea6cba7039f67"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.x86_64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "5c5e020fa7d7113fac272c8a3d14b8eeb3f5f954"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "679ac6604c0b8df31afa71e5f6ea8c750c7e1483d0d3c1ae1ba332f76fcc6f26"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.x86_64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "c84b7ae809ae83a4065c8a2299a4f0291af84f86"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "2b75399b215077e9d5fe0b40bfad820fb99b693c5bdeb2d7947d6afcfa2c6b3b"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.x86_64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "1f3e8a7945b4b76a7a1e7482d26a65d04ea49a96"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "9769726301d3d2de820f82fbb91fa453203a744654ed2b7ab03e384b406637e2"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.x86_64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
