[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "f0eb5693d6acf26b57dead6e490c9fb24897aa02"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "377e6e0c01a7dde17c4c510cdd9ad55fb19798413721f4384d6ea14218bc487b"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.1+0/MPItrampoline.v5.3.1.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "0de072fd0fa5f01e480b7d03bc4d317a9c970ef7"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "d3f623fc372302b030e9cbe0552ef207056f4efd515e96d163bd59bbe0bdce94"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.1+0/MPItrampoline.v5.3.1.aarch64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "1e4a645e159428bc2ed095a36eff7d1bf0933675"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "4628fc83414ca7357bf2d31506e6c9c87d32c4ef87ded6467ae47353f90e2d7f"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.1+0/MPItrampoline.v5.3.1.aarch64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "958b1a10a3fe1ba17af312baaa32b4b5c10822d9"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "7b2d144cd3a356aca76ff71bc09e80b2559957bb40fe32a913ad5f8298213636"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.1+0/MPItrampoline.v5.3.1.aarch64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5f67d8a5c7779a56592dc5eef674c2bd92f78169"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "e095fcd3ef1eae0a6d297d8e80ab2bb3ac13e5a1f7bfa047eb89676d9083a363"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.1+0/MPItrampoline.v5.3.1.armv6l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "eab72ea3b8368b8903cde7cc5846bb9914024adc"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "73abaa2daa3095e52e83e5f86ee59b4ea0c354ab0e6a3649f5475d73c8d439a4"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.1+0/MPItrampoline.v5.3.1.armv6l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7547b2f06a488c48324287ae06872fe6ceeae015"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "b9c41ed478cb8748e1f951ebb231ca84701e520fe4cdbcfe0117843f35f41d17"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.1+0/MPItrampoline.v5.3.1.armv6l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "06c149277337af980656fa63dc3f77ecd877d482"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "72f2a99476c2d29ae0fabc4eeea50c44699d70005fbe9ddd6a2ca71d517ba9c2"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.1+0/MPItrampoline.v5.3.1.armv7l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "777422c5ad9e40364f7d87d375a75db33ffcbe6c"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "4286798bf4a3e3e124b998e3870fb33ccf01493a057a66b6fe27b369f9e0a5fe"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.1+0/MPItrampoline.v5.3.1.armv7l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "464a8795577b29c41ce2ce368e19efce52ca32e7"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "7d2b513400e43c3a4355a27c6f693e65cd00784687da8a15d757500432fd9d7c"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.1+0/MPItrampoline.v5.3.1.armv7l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "4e8e6e69f03fded56210bae23baf44b77efee542"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "963b7e6f4efef81b391f3cd711cfd1b35ead63c0df72d77e53beb9ca93850228"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.1+0/MPItrampoline.v5.3.1.i686-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "d7c3dc9ebd06ed019d58b45e2ccb2de66abe0f89"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "fdd5974310f7d72c2a205df2f5968049177feb4c23592d494e819ca553a5e695"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.1+0/MPItrampoline.v5.3.1.i686-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "132716323a2342a3194d452d60cb64fcd59e00b9"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "d6eab782663b2901dbc904cfdf71f64be140c3b1254967a91561f44c3fb7e226"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.1+0/MPItrampoline.v5.3.1.i686-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "0857f4a934274e2bc75c712d148b7b5fecf4ac7e"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "1aaaecffa1f407f153e743aa8258f137bc1733e8a439c54642e4a85878d77f31"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.1+0/MPItrampoline.v5.3.1.powerpc64le-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "d64b471f5a32e4859be4d6674c68496d3ced3a03"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "dcb5bff81685cb957e212bdae2c931863bfbca91bae75d3b6108581c53ee6edb"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.1+0/MPItrampoline.v5.3.1.powerpc64le-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "157207e9aef21428771350b23a18f6e2fb0efe16"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "4070e602a1cf0cca9395c0874442375c54b1bfaab28c9609c0345894d5d3e356"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.1+0/MPItrampoline.v5.3.1.powerpc64le-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "a456d0174091fd1487da76a2db44f675c28e2843"
lazy = true
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "865c57c6d6c466ee59909a43829265d60b709af7e568db5c50320410dd2e2216"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.1+0/MPItrampoline.v5.3.1.x86_64-apple-darwin-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "6886c94ba27cb8f9dfb307e46435550f92d615b6"
lazy = true
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "107cb95e4f95ecef0750208fa5632de7269950197cee668a9ed4538b78ef426f"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.1+0/MPItrampoline.v5.3.1.x86_64-apple-darwin-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "7cd3346b55f76bab81cdd6356e9b8e03f4e026c9"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "dc0e3da397f81f502775714a215659f1bd256f68076722dd9f0cea0dd01f6e65"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.1+0/MPItrampoline.v5.3.1.x86_64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "d9d6fa021a48b0cb0af38bf331d39d72572682f0"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "c5e9c5fd412afb00e321bc1f8730b303a6629e103c1c1a6e2784d791be998d59"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.1+0/MPItrampoline.v5.3.1.x86_64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "7bf77e9be3948c51838be1d0e3ffb31e6f03f6b7"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "db7f95572d3fb5f2215b0a62c8a6bde36cddbf1035ea0bf444236c8945a392c4"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.1+0/MPItrampoline.v5.3.1.x86_64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "18469df774e08acadf055c657e41b82705c9a956"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "55dba77bf6e02f20978b1fdad25795727a462b9f0c2a45c70ace98fc53517fce"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.1+0/MPItrampoline.v5.3.1.x86_64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
