[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "2630c2842ba87a6654525d24cc58db487e773654"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "e94764d46986a5983c4e9547e9b9fcd19e3b91a1adce219ecda279ef38a2886f"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+0/MPItrampoline.v5.5.1.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "f49ff80514dceb331bab1736940c6509d7344b4f"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "15842194026c8996defa7c5bf1928e3f3d95097b7f9c4992ffcb1a6d0f9abbc4"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+0/MPItrampoline.v5.5.1.aarch64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "9b0e697ca48b9c97d3c55b86ec2031b5982da6b6"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "c31568703bc5cd2b87f54021c39b4c5c207982bd66cb9aac1fac1c05409cd5eb"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+0/MPItrampoline.v5.5.1.aarch64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "00f7c163ac55fa0b212aaa4e75aa2535f2b46520"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "c090d67f5c01731f6f2b5df48851f628ec6ef5b13e0f80c5b5a6c9031fd12841"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+0/MPItrampoline.v5.5.1.aarch64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "8b86a5c9e6fcb451f73877f4c8b97f78bd5ce73e"
lazy = true
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "freebsd"

    [[MPItrampoline.download]]
    sha256 = "d9de7722fe7c2f74a889c27e55ef81201e27c9223274feded856e177a11457f4"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+0/MPItrampoline.v5.5.1.aarch64-unknown-freebsd-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "812992c3ed7855d32a84462495e9649e3f8707b8"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "freebsd"

    [[MPItrampoline.download]]
    sha256 = "fc981522e04a74c619a1029bb0768ba7a369770cc28f81b9ac490f91018ff9b1"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+0/MPItrampoline.v5.5.1.aarch64-unknown-freebsd-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "497bad0c142fab6a2d6155cb8439cecd8ad3a14a"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "a9de12cefcc680b0decf20d5aa593cbb08e2e1b86cecc7c7956ef3f78fbfa94c"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+0/MPItrampoline.v5.5.1.armv6l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b33b5fbdec0e9c1640b0523ca93bf3a625b0281b"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "7341435ab0190cb5459cae0b3ddd893b59ffb6787329936dfbf7e82071f1b293"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+0/MPItrampoline.v5.5.1.armv6l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "00241baa45c2ad65a4ddea15b47d76ec87a1bd23"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "cdff308d96bfc504f4377496799b1f3104c2aee2636f95588dc249e5bc2f2441"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+0/MPItrampoline.v5.5.1.armv6l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c604486721a2f2b226a695c7d3301fe935a30c14"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "9f8db5cddd163b63577fd8f62650ba7ab1d58025329402c93b952e332ffdc407"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+0/MPItrampoline.v5.5.1.armv7l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7700c33a6653ff7fc268e6983f8656990480a968"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "f2e9f000c6dc107147a2ddce0693a5a08c881b7ace7ebec33e794ea32b32cbc7"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+0/MPItrampoline.v5.5.1.armv7l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3bd8a994142a88ebdb01f2dcc5565619b6305975"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "c5ee8d7f0700c4d8da62699cc572c25c51b9bb445a114e3f26cdb95340c5cc39"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+0/MPItrampoline.v5.5.1.armv7l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "b789c4e24e3aa961f2db65e43a302164b1ed06e9"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "913c71012bf8d35ebb3b6f9f48ddce4cd691d46557d373804ce76f58b3fa49cc"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+0/MPItrampoline.v5.5.1.i686-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "8ff303145d94e472ddf2605b2075ab12e246d9c4"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "6b7f0dea608ff2c5f5c8cfc564d2d36d80809b170bb0a7c54bd772a76ddb0931"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+0/MPItrampoline.v5.5.1.i686-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "868bffcb563c8c3bba7bc808832ede141e80f3d5"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "ab382cd318ceffb254964f06926edc0a94256f8fb18d00803cf6eefd25e6805c"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+0/MPItrampoline.v5.5.1.i686-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "dbbf2f65286186af70fc36e3b3631fde3d3b2d4e"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "9a0dfbe29a6f093b78e73b3e3674a01b8d95debc40069f2103387a8a67dcefdf"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+0/MPItrampoline.v5.5.1.powerpc64le-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "80999647afe0dd89f25b6f787fd3974223660749"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "666449a662a2ae3747d0ef2fd8324e3813ad72a881bb2c1d00bf5e5b80f58f3c"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+0/MPItrampoline.v5.5.1.powerpc64le-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "77eb344fc2aec55e5d413bab015e7e94534fe344"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "42db011e092f7d15ae0df45a8e142bfbae765d086f92cceefd1e5cd94c28fb11"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+0/MPItrampoline.v5.5.1.powerpc64le-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "7a6fc5804bfb590aa5486525f2c29444c07adb10"
lazy = true
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "3d734c84f2968acd272e99736b9d22725095f99be29c95ec3f1cd9eb3e8a8f2a"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+0/MPItrampoline.v5.5.1.x86_64-apple-darwin-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "2ad89878f59e9a930495f09f8605ec63b1b4f2e6"
lazy = true
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "7629d1e79586a0005ac0337de08e0770aa15a205b5b683bfccb462d58c631ddc"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+0/MPItrampoline.v5.5.1.x86_64-apple-darwin-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "8172f7ddf65acb079fd5534bd5bc3013d91d8d17"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "56dfc0e8df78bc16788b1477f0ec544579a0617833bac7141c8b38670794df24"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+0/MPItrampoline.v5.5.1.x86_64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "d12c97dbb40edd93c2941565c61a593e3968444c"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "169bcac252b1bc0d515243979dddedb84213de8483b49588818f3b38a7ca10d1"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+0/MPItrampoline.v5.5.1.x86_64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "a0e773bc5947a29fdc4b27d0e197c61bd3e10f2a"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "737cf84fc80f283fdcf3d0a703ceefda24672401a8fc060d5fce004d7969b9af"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+0/MPItrampoline.v5.5.1.x86_64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "c1dd1c30f308ac0973e073ac10d771bb29330511"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "16c46ccc8817e7d2975979fb5b47f598e79ad87cf2a90b900c449294dc211e1c"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+0/MPItrampoline.v5.5.1.x86_64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "bd1cf8da23b1f8d355c27397fba6f411c70c8e23"
lazy = true
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "freebsd"

    [[MPItrampoline.download]]
    sha256 = "16de304774acc6a32d8cda46b7f25a7be4f6aeb67898c11f8e4988b2a55ee93d"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+0/MPItrampoline.v5.5.1.x86_64-unknown-freebsd-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "bb87a3c95f5874a6d2048210eeb9fc74db51d7ae"
lazy = true
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "freebsd"

    [[MPItrampoline.download]]
    sha256 = "9fa95343d7927d4426836599ba3950f131801627da2730e9f25cd3c1036dc1fb"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+0/MPItrampoline.v5.5.1.x86_64-unknown-freebsd-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "51b361e143a5af46b99619eef77adee40d0350b3"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "freebsd"

    [[MPItrampoline.download]]
    sha256 = "aefc869ff5004a97c18fb070b50faaf91f4f658c8b61f94e6d4a3e103306b7f6"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+0/MPItrampoline.v5.5.1.x86_64-unknown-freebsd-libgfortran5-mpi+mpitrampoline.tar.gz"
