[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "c985754f709808d0e05564f532abfb4ec6ea45a3"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "c0c8a2349538eae652871992164645f903f67ff0d60028214451a9ce8db2eb03"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "96faf584104eff435da437d914088aee6afb3b3c"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "95e9b0e5149826c5b6b5f9097c2d65bc2b30b1d2b52b067e3adba98a738883b0"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.aarch64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "31967dc35851aada9b2c911efa789d7c038d6414"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "c9b6f173bec9a6205f9b3fa85e6632556461d0777c2bfbf4b3d1a700103aca66"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.aarch64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "9caf04ee70ebc433ee367ab9ed435b09232bcafa"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "016519cb2a07c72909f96714721734b3fdb7ecc8cf5fcc9dbaecc709bd2e564d"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.aarch64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8f09f932c5e7925b4eb25f549a1c409812fb75cd"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "a34e1afb09f3372a26904c375fac773428e7521b11170ec60af547c464781cc0"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.armv6l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "37ea8e81612549b577773ce5ab30d28a92343701"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "7b5eeb14f046709745c9c64e4c1a2859d4fa585ae121ee5818c89f6cb136ac05"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.armv6l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "584591d1b04063279042cd4ee174c36c8102c4d6"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "281a709cb955da4dbdc25d40e17063cfdaed60c71f9c7c46a8eaaba05767ffdc"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.armv6l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3bfe754f57a050f3da4bbcf361fbf2c1e64cf85d"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "2de53e986f28c9189cc15d60b10a6db015e6bfde35d73c5ba11a0610ca3eb52b"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.armv7l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "db1f5c3c2206e4b7373792e7295ef8d5fc54ffc2"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "0e4ffd353e3996f5477922b10d90af6724eea92b57c8fcc75df0effc7a70b986"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.armv7l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e17397b5ee31ea05fc5272cda6ea35597927625b"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "ebb5c03b08731053ee99912f60e1230ab282aabd50a7431ec735880cbd6e789c"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.armv7l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "82cc4d4c35f5967a27ada6360292bcad5212632a"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "1addab1da958ad9941697f03e359c4595d6c7778c3ee1d324e2188c7d90e3b60"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.i686-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "1d1fe3431a168eab11e7b8948886cc8e703f7059"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "77886d036d53c55de417a746c72d1a9f9a49078c416e1e96b267b159286557c9"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.i686-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "213f293324b4c3d55d27156fd68452412a1fb0fb"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "afbffbcdf0671a8a042b492c906f6c9d8d0a6889170dff266e8d3f1705a121af"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.i686-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "e3659fd43e273e3aa8692888a3a14a6911197828"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "2c70ba5b846e1d46cd6e54a2983149cf7c2a72aa2b78687b00c534464853876b"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.powerpc64le-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "cc979f45c5348370080be0437e6c010ccb3dc559"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "e08227373a5d8ea4d4814f82183193829bcc0f0811f03522ab8a8d26c9cf211e"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.powerpc64le-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "2b0d01468c869d8ac53a071d34fa1b56ac645289"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "61e2e1af058996af621d2462ff51396e307dcf70d388bd428222f2fe1059ad23"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.powerpc64le-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "d43826df6b56411e528bcd67c873891e599934c0"
lazy = true
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "3e3436578b1d25c23665c66779659ae36d4ae5927b3cc559b52cbd8f8e2269d7"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.x86_64-apple-darwin-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "83fc757b10b020694a40138d67533edc7dbdfb90"
lazy = true
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "cf0baf912552a009b81ad47efebefe13c66e1822097ff635119a333f73387eee"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.x86_64-apple-darwin-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "bb28c6310eee71f316dd5a5bfe78dee2d4ea9f3b"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "8cb96e9f667f16f1b12d41126c35ef65dd41d20a0ebb28d576910abd6e57474b"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.x86_64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "87716cb78a8e84d88283a8d736c0c37ce4e68cc6"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "64a4589bc6b7c8d8ef58d297af0e70b051cf6afcefab5834e70b1b37953ea9f7"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.x86_64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "a7881059ec46bf8bee4b97b584f39400a6d593fd"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "006e98ad05331f19db310154b35959d3c09fb557df07d2c7ab48e5429e758dea"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.x86_64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "6d2b2926070a591b11b6cf21cba65b27f4c3c724"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "bdee92143977db6ea3e1e2b08f70bb8af8b7b0ed28fa2601ed305789567533a3"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+0/MPItrampoline.v5.2.1.x86_64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
