[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "c9d791f9f13674aaf39ea223884d130ca6c8929e"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "cfd1b2a2a9f71cd6d217f0cc75da257491ef4ee19b31c50ab46a14719b1cdf80"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+1/MPItrampoline.v5.3.0.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "de9816ecf26f69e959d0931d339083769da4ded1"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "b312c18f9e92b210ed8a524ed41034ff4a03a9287e95222b5a55e023b4bc8e00"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+1/MPItrampoline.v5.3.0.aarch64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "4167ef1fe24676d9b18b3de265e836f35d56cf9f"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "9148d607c10a11d73960772ac1d751bcf43995d0c1e4f3aa1dc6c5a633e93fb6"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+1/MPItrampoline.v5.3.0.aarch64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "d06ac4132fdece7ca58b06b9797d7dc75a2d0794"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "66cd37a30d092cd6fbdbd5fa36c6fc4a3d4356675984f0ab82de24c8361d1d63"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+1/MPItrampoline.v5.3.0.aarch64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "587bfe7d3dd0afa760f6057ad90fbe0f727ba36e"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "3146e14d50cc59b386c0511a40cdb40d287e689c6d5c5d07e554e2ad4ce35f91"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+1/MPItrampoline.v5.3.0.armv6l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a4c1036a524cc9aa0399219789bbf019f5098dfd"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "e6fbcc853afef9d2e00bdb5dfcd42466f40df258e2216c115eaafe211095c008"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+1/MPItrampoline.v5.3.0.armv6l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "35d74f0742128d44542bd5253ab909be51b5f899"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "ce09b98a7597306fc982d054687f1c805a0cad6b356dd39172b31284fb43d344"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+1/MPItrampoline.v5.3.0.armv6l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e7a1e8c2980ef6e1fc53b010bf7f0abb7f70ac03"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "0945507365d951eb6cc549113cd8ce96301748a994278f5661c875f6d9c498c7"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+1/MPItrampoline.v5.3.0.armv7l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "905df404475fc47b2d16b00b00da406f655e543c"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "d38d92b3526f6a8609420b0d5d479c82bb904187824c733534a3f0f282383d1e"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+1/MPItrampoline.v5.3.0.armv7l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6d3a992d78190d987223991f05eab2a5bf530cbe"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "87e56a70488be360130d9105a1755e621d1cf9f460800121c18a23b36b924908"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+1/MPItrampoline.v5.3.0.armv7l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "a18b3e97bd5f323809759c701bea92af9656f048"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "0e184e79a8888daa9e778c636d7180e64dc1c364a03d658355815a715c9608ab"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+1/MPItrampoline.v5.3.0.i686-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "645767fadc94aa771e41ee14691d8bc075979de6"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "f595287eb27e196f2623f15abf4c45d8c8c41c80b1c085064516a3377507fbc4"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+1/MPItrampoline.v5.3.0.i686-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "4e507be2ae41f3377e06a8bf758581f632f5cca1"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "8344c66e6a585a798399fc64a59f66ec30b9a38fc65bdb5a5634c61b7ad5280b"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+1/MPItrampoline.v5.3.0.i686-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "7b381b8d6df6dd162e064936a39db17496b9efe1"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "5ba6900440410aab17606e7d5b161a8026f481c6cff615e101a2d035d5722bdc"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+1/MPItrampoline.v5.3.0.powerpc64le-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "64a7eeaf070286a7aad7df8051762ddaacb282aa"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "e26c10318ddfc4ef06560aa9c8bdc7100925e0da4e7a576a58efd85ebc3bb326"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+1/MPItrampoline.v5.3.0.powerpc64le-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "a04782f3aa636eece8bb93bd2958668ff429733a"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "4516c4f922723f6fd648c0b2bcd1fea0cd4a697d92a9ad64b3a152d8adfb4acd"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+1/MPItrampoline.v5.3.0.powerpc64le-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "135428a015aea153d775aa99bee276e97f104243"
lazy = true
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "6221928ab1eedd56b1a0eb7129699ed3d44d5332cb6a1d57663d9a490886ed0b"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+1/MPItrampoline.v5.3.0.x86_64-apple-darwin-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "2d5c98de3a0e1ac5241a600ff8705333219d5d80"
lazy = true
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "077a575cc9c3dcd0006d4243af1ce5d9a8a88ba7f2953bf3c8de1adfec579385"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+1/MPItrampoline.v5.3.0.x86_64-apple-darwin-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "73a45901bcdb4e494c21aa68c8e2153276583bac"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "50384538f6e09573d0ccc791834ff88a194b56b8b519a19500de4a1db2f5eb68"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+1/MPItrampoline.v5.3.0.x86_64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "c249afd57287aa667ef9c6413e962a08d1d3758c"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "96f3c7e37c178bfd4f818fb49afac44388da3335c225fb1cbf870e6a5034b215"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+1/MPItrampoline.v5.3.0.x86_64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "2a0aa86b83bfb58567799dda86e06ae711402efe"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "ae073abb649a12fdc105fa8281aec4ad99d33a4fc1d09ac7c5746c5a3df26f52"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+1/MPItrampoline.v5.3.0.x86_64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "98bde42b7d5699f8339b4bbbe9f77ef7cc103630"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "c1191959a9853ec829fecb3679dcfb02adbef589bc4f63834c2dbfd75bbfdf1d"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+1/MPItrampoline.v5.3.0.x86_64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
