[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "3b6c29e513541fe234e42272957e75f9289b7d2c"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "617d2e49830b58d4f4fb3c59a67adbc05f95fa370e38c553fec0440005c5b9dc"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.2+0/MPItrampoline.v4.1.2.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "d79a7df2d25103001b6cfa8b178eda5694d69c0a"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "0c8275177b7d6358d0bbb26d840864b04832d22bf01f607864be32ad7fcc20c9"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.2+0/MPItrampoline.v4.1.2.aarch64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "8bed1cf1dcc95e532307b9b5a7555f024605cbef"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "a3bfff08d25323d97a35b0694042d864833b4511199c9122bb791fcb90dfa816"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.2+0/MPItrampoline.v4.1.2.aarch64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "86980f6ed301b2d2457f50918a3a70552c7a97e7"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "3cd3094886c5fafe1ac6a6be4b7aed2ff1afc477938c123350054ac589374ee5"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.2+0/MPItrampoline.v4.1.2.aarch64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4558157b3b4af1c14643135fad1c96d73378f913"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "70fea19b1622c6a341f8baa8ebaa07228f86d2e5856c6e8eaf3d54890d643e3a"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.2+0/MPItrampoline.v4.1.2.armv6l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e6960e254cd41c9aa6b8ed15ba089e8a21b82fa3"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "0905b3b9dc1fe659d96060cb972c485eae240311e8cd7891a405a505edd49034"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.2+0/MPItrampoline.v4.1.2.armv6l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6b2ec23b4c82e6970b8ae1dba7c2af234e402fac"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "84ae3b47ea9ddd8f67a84ebb71f9d878a897ca09da68443405632a85f52f2f6f"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.2+0/MPItrampoline.v4.1.2.armv6l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "844e18e0c61d2ff5e476dca34014df45fd64a95c"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "1bf945805b5236f4a2054c36816eb4c71a309107f510428044d483981f356a96"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.2+0/MPItrampoline.v4.1.2.armv7l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "20402f31161a4e5ce5c58b163b12a6c43dcaf941"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "077fe8ea468c72c0f2469633e90aa75ef1a87a3dbf8a9454c671e7eea2d74864"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.2+0/MPItrampoline.v4.1.2.armv7l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "17d44095f021e1a11eb2b231dfd8c4ea67631f21"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "e0f5f3386eb5e8da76291085e7408aa4e2c78f2322a207df30a9901c9d92c665"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.2+0/MPItrampoline.v4.1.2.armv7l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "aba2c4c88935de7ce05e7fa475e67eb0744e537c"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "28e97bc0fa8a4f2e286f4455255d90e414f7b5ea8f5be460fcc152caa4e23ab4"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.2+0/MPItrampoline.v4.1.2.i686-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "818b241ee9afef2166bae1d52b8a0f9d23715bdd"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "095c1591a4cc7be15fba38a68f58a6c26569464a3325ff1c754151a9771cfc58"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.2+0/MPItrampoline.v4.1.2.i686-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "f5c2908bb541bf3e4ebe4e6dfe5ec05e3ba48058"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "5922dd07c0b57762d29ce658989011dba279233089811d1ea27dd567aaefc745"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.2+0/MPItrampoline.v4.1.2.i686-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "fd19ee3ff383955763d45644d54c359ff49e594a"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "4d4ee7995a51843be10821bd91190175f6ee6446e6053d16b29c1fd6e8589bc3"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.2+0/MPItrampoline.v4.1.2.powerpc64le-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "7545c580f2bdbe09d7a2567d826743227ca56cb2"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "2fb7fe6c56e8d037c9fcaa3db79c4cfec447351c64b3523c9159d06afccca515"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.2+0/MPItrampoline.v4.1.2.powerpc64le-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "e5664ffc3e17016deeae08f813c58529d912961e"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "ddd5f127805d21da628c7dda1ca570dbd88570d4fe1fb3a60ba236c3ca6ca8db"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.2+0/MPItrampoline.v4.1.2.powerpc64le-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "9df3be7b9ed3667c6ef9afd1913180870cec2aa6"
lazy = true
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "e0764db35bcc3a5f7564c1280c56d184bb33c3207046e18f86d9391dcb4aee3e"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.2+0/MPItrampoline.v4.1.2.x86_64-apple-darwin-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "5d301f4586c4ee216cc7c9ecfea3f5adac6e91ac"
lazy = true
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "694625b69bc10e111a9a69681471aff7637c0a0029f8dd535a703d6afd22cc7b"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.2+0/MPItrampoline.v4.1.2.x86_64-apple-darwin-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "4becd0ae7d4bc096396ea2d355518df83fec643e"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "729e7fe9afbab8b10713343e363f2cc0652749a6a0dff1af49efe7c79d34d215"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.2+0/MPItrampoline.v4.1.2.x86_64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "d952abb8b3e7d5c54022c02c5b674b96534919cb"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "81c9a2d38d2c1016dfe2c37b069c0515e9c8827bad3da36aa5a41bf0386c2dfd"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.2+0/MPItrampoline.v4.1.2.x86_64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "63c6f16fc3b4ec31c214a70e8c477f8c7ba35d3e"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "460a441368b76a8eee7d4870b7aa2d7054016002c72a9d84e4e730ff419449f9"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.2+0/MPItrampoline.v4.1.2.x86_64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "4aeccc31ecbeb726647608113e0129bc31a84ccc"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "108415154d51777a352cc74033bd858587d1b5d73833a9c94a749207b0f75a3d"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.2+0/MPItrampoline.v4.1.2.x86_64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
