[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "b17103342637d28a0a5c1a7794c336e658a935f9"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "8cb553ea43dd8e2d03583a036796393457a7bcfa4ab2cbdebeb80b0218644e80"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.3+1/MPItrampoline.v5.3.3.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "1d324cf9bb5c77eba7f35f5c0d3be02f578735ce"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "56a1a47214a2d66401e1fe2ebad79f6827d4e37344df818d4deb40e374c09690"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.3+1/MPItrampoline.v5.3.3.aarch64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "56d1c63649c38b5570ecb185cd627169995273aa"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "1361489591292df913f71c43c2176712bc8485f95be5e396fa8af709aa21ff8b"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.3+1/MPItrampoline.v5.3.3.aarch64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "a37dd9391c462ae7f79068430c9b83f2010b11b0"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "5e098ff84ee4c42ce6848755c0f6d31cef07ae4bb2860a54e6dd438e7400ed5d"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.3+1/MPItrampoline.v5.3.3.aarch64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b12250bd2351a188251345713c61c79bff3261ba"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "059c4ea4919a330c26edda7d67698abdc7baeffb2b1e6275ce2497f9919d5fe3"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.3+1/MPItrampoline.v5.3.3.armv6l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "63a96bf783a8ad2d6fe411ad656904b36e5cc81d"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "f5509c0db66dc4d88f5493d70e0f7a45b27ce6e3a3e6c36a3b33f5c960f461be"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.3+1/MPItrampoline.v5.3.3.armv6l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f36baa7002d279b09b8799cc1cf26558d144bb71"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "8393e41f1693116176f9aa72af46faa1e1116ed20bd01180cf240b8525337f8f"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.3+1/MPItrampoline.v5.3.3.armv6l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a33eeaade06159235472186ba12bb14f8cad9f66"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "7854c555eb7e6f17fb69a2b5e449cb42d4900a2e34590c85ea4f9fa15dc453eb"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.3+1/MPItrampoline.v5.3.3.armv7l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fd5a0ae4178fd958cfd59e5c1299269c5a72465c"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "fd24cb922ad2dfcbae14b9a7864ed2d8596be837dc45b4b7928907dbebd2c3db"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.3+1/MPItrampoline.v5.3.3.armv7l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c511edfd85e85bcbf38eacbdae387d2a82786ad6"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "5dd832b70a272762a4ce53bbaa8054735661a54ce944732f33e29087737450c7"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.3+1/MPItrampoline.v5.3.3.armv7l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "b34159ebf463f582ec3b058a4b44511ce51cb5d0"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "7b94fd4ecddfbea2ba75f324c434603fcb4c4f6b30da6d3003d4ee508702a3f5"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.3+1/MPItrampoline.v5.3.3.i686-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "fa42bce7cc1e079a6b8ac3345812b3b93a91553b"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "a8ca5966d57800e6f6e0443f90a72781c8318d4f04483f3dacd00b89b94ca705"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.3+1/MPItrampoline.v5.3.3.i686-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "14185b4624e6b5f75cb50d09b379c10ae9757830"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "6b096a2035ae82ca09eb502030d5f7034485a241eed04503ac61c34adae1d9d0"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.3+1/MPItrampoline.v5.3.3.i686-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "441bc4ecdb4111aac6eaa932cb2eac91457a0055"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "55e454baf3c0e54be8d715690db18900790552ecf68fcbf37825b4c4b2540c31"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.3+1/MPItrampoline.v5.3.3.powerpc64le-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "45477b389a7869c6c827c32caa41e5cfee88e54e"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "429cef376bd567b65e0595cebede2b8f0e08dd27c1a2395eec965e80cdd4835c"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.3+1/MPItrampoline.v5.3.3.powerpc64le-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "ee47638aa0f7e1fdb61bb7b60939602fc137c9c1"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "35aa7d277c157dfc6b94e436461f6b1562394fb1fe01b95f7cbd70ca5472e07d"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.3+1/MPItrampoline.v5.3.3.powerpc64le-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "04558f3a003bb1bcc07df4b1a2b28ca3ac616114"
lazy = true
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "3ac57145d1ac1147007d0799ae34a8acd59ebaa44510ee033a0ac6cf363913a9"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.3+1/MPItrampoline.v5.3.3.x86_64-apple-darwin-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "23b0d277cc7867d8f2e5e4402356f0b4298f099f"
lazy = true
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "6909a8c57eb925dea8333328662f17c8272c34c12269c2c1fe9af5e151fc4452"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.3+1/MPItrampoline.v5.3.3.x86_64-apple-darwin-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "06cfd6560e463df52d97803fa35236dfe8391f74"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "c2a7afd135524e9dda4e9cd4b048c30a420f5efe5b1fdc6bb43500efdb3ce171"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.3+1/MPItrampoline.v5.3.3.x86_64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "84571b5452628acb9db0da3f8c02e1322237e295"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "5dc4c52ba91a5c4f9f115bf7e4a67b0a214ceafa36fc7f30d48c51f4bf31d96f"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.3+1/MPItrampoline.v5.3.3.x86_64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "63c8b245b3af5c80b7d7347debd56a21a7eb01dc"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "38c9c6e4ac2f109df0d99b1681a3dc4d73072bde2d9fa84151c79590262e06f1"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.3+1/MPItrampoline.v5.3.3.x86_64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "4f8b0af23db9ed8c6049fa742d4d378a8cbc3dc2"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "54deba42327240687098aab2a1dfc5263126cfb5a356b9584e26a23956f15159"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.3+1/MPItrampoline.v5.3.3.x86_64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
