[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "c1ee7702978a98614459bcd0ab394e65c1247d83"
libgfortran_version = "5.0.0"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "a56a8da39d6f139a3b0d2c04d2e0f7fa725a8d38447cc955fab0382cb8e93653"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+2/MPItrampoline.v2.0.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "cb4ab6823929f08bcfe2feab2ce07d1b711ee712"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "3249e1fc5ed3ec483db636fd3c6d15aa7a8efd6c71bb223c8678f06959c17315"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+2/MPItrampoline.v2.0.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "5074df43b2e73d221be70160da7ee515ce2770b4"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "ac2fc59cab556cc30f1ebbf37ac95462e40e2e7f07cb6b9dc324e91d742eb541"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+2/MPItrampoline.v2.0.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ce5619e91dc9c523c4629cfbdf6a6e54bfc3e7c4"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "ca7b687d47dc90f8c0d1adb9b8b4ff42cf590700adb32ddae0ac95688fc8c6cf"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+2/MPItrampoline.v2.0.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9b8223a0dc39088d8882d73e81291e6f69d772cc"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "5a182fc0d2bf9e719d836301df437bc15543452e028ecf5fb9f9e383052dd4be"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+2/MPItrampoline.v2.0.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b65856c5e5f5bf8288b1cee231646ce5ce79c965"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "805bde3755a8bf8ca23caffe45eb3b6f9347eba61fb538bedae9d980402563ea"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+2/MPItrampoline.v2.0.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4421eebf52c953efb905470974aed1c1e825296a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "10644c6edfb41132522844b27d1b905c2b9364dbde5cff372fd9b82ce26af5a7"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+2/MPItrampoline.v2.0.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "f64e4f54962a68b86d56add7413e3cde3b408270"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "e19cd228b138e526ed159ccf0d3691e99288a51c01ca6670741753f03c6d3276"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+2/MPItrampoline.v2.0.0.i686-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "fb3732f23ffde21f34d2d4500fe32a0652156699"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "34147405335b2c28abc814d76f459f1a29dbee33cb0db6c5a54fcd84390f2ced"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+2/MPItrampoline.v2.0.0.i686-linux-gnu-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "bfdb8ef3456a951260372a804cf4e92fafcebd99"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "f8936b52c9d81718487989e05edd6d0555f0f90781c6caf6b2f3231a8e1ace0a"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+2/MPItrampoline.v2.0.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "1cdf84a50d60213de2dacfa93aecceb728148c38"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "731f452799ebad7ee8814afde7236ef1fcc9f1e7a3685c535c42fd36ee40bdd4"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+2/MPItrampoline.v2.0.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "9dc293b88030d7a382a5c93065aa9a05373fcaec"
libgfortran_version = "4.0.0"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "f0362b7789ee063db139322f0580cf4e556b9bb0cc47d581d36d1921d7e1d49d"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+2/MPItrampoline.v2.0.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "13ee8881b34d36859bb9be5b1b504622064df6b7"
libgfortran_version = "5.0.0"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "27a1663e5d59298ccde13c4a1fecb9efeb8e7a77d61966c6a8f0d06409e0fd74"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+2/MPItrampoline.v2.0.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "1413c2a735ea4915a2fbf454576220cb16e5bc91"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "6eaf31bd138b50b50480de0723caba7303d9e608afd779bb81733e351f913ee1"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+2/MPItrampoline.v2.0.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "bc9b9672e083ccc28df578aa22d3a6bd5eb55637"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "865de9210446b7527f5dd6d10445119ecf44b918b457c77d115ec114064bf96e"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+2/MPItrampoline.v2.0.0.x86_64-linux-gnu-libgfortran5.tar.gz"
