[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "937a1b6e2a2ff113157649d4a549d65aa0b9debb"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "0e9c56e4c0078d7c06e4ce6b5df7678dc40c1c7121d4956353071eb584a003ea"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+1/MPItrampoline.v5.5.1.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "8877a91f3764ad94a8435dd1804e69c8cc0da9cc"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "e7b9f0a407875f4c4ec0f788ddec88c5e97ae458fbd40e4f58db3c2b51dfe323"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+1/MPItrampoline.v5.5.1.aarch64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "a6e98792a2e5d318218dafc5c75d1d956d50e19b"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "243978a92f76431542b5aba5972505358f88f22d97fd5d8a7bff55d839962451"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+1/MPItrampoline.v5.5.1.aarch64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "84d3412b41bea848208ff18b69c7749f0b74d3c2"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "ab59c237fb897431e08c9f87394d6f5222b8e291d442f244e32423dd93907dfa"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+1/MPItrampoline.v5.5.1.aarch64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "1f4b13706eaa3d25a8299e106ba1edf2d2d04534"
lazy = true
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "freebsd"

    [[MPItrampoline.download]]
    sha256 = "295a3812164f582e56a4404e87dab75f92a791f1617cfc3ec67a36dc7dbb150c"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+1/MPItrampoline.v5.5.1.aarch64-unknown-freebsd-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "3b2bd6e4232d8ed48ed889d7939b2ead8fe50502"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "freebsd"

    [[MPItrampoline.download]]
    sha256 = "785265af079c88faa2aab725d46db7ad50efc56d327f3362690d6b472158b7d1"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+1/MPItrampoline.v5.5.1.aarch64-unknown-freebsd-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5f5b36f68acb6db0326353cbdf5b341a16a1edc8"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "194cb6acf6e68682a76969fd9f6d61172b58b55fb345abff225ec5fbad7d2d24"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+1/MPItrampoline.v5.5.1.armv6l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6056b261a4227009a18f658c443fabe30ddc1687"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "35b651c030b2c2ad0debc5491077428d07afdbb9003039088f567265bf7746fc"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+1/MPItrampoline.v5.5.1.armv6l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "813a8559d2e243c4788d7c6d29aa976e63b9a802"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "0f7380951ed5325ca3bba31076254a8a00ec1b6de32699cb60c6f3d80bc68853"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+1/MPItrampoline.v5.5.1.armv6l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6bc66bdaa709c1402ff6eb1bf3825fe8ea139890"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "88afd02af0cc13752d14c8773ae1ae5734719bb3a0b5b88226c1a34235962410"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+1/MPItrampoline.v5.5.1.armv7l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7137d4bcbce4c8495483980175a9fb57dc40b086"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "7ec74824bba9e3fad2b6f91658af943a733a1c37966f03ab4ca5c25d80585280"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+1/MPItrampoline.v5.5.1.armv7l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "82ee2396fbe1c79e6ab51e5f9f431224c367fc2f"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "06cbb85f518f531ab71d463ee717f466a84f311cc07fa56a0436138877359775"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+1/MPItrampoline.v5.5.1.armv7l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "a7f1bb66e0c1e75b1c6c720731ab8cc28546f4b3"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "41fc11d86ed18a56c2cd3424becb730d5c0004ddeb557db5194c6945f2805e58"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+1/MPItrampoline.v5.5.1.i686-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "81345cf862596c76e971ddc57d5eb35170284970"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "6b411275fa743fa2790d82e2bfc7fa91d24d8281028771f625043fdc27bfa550"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+1/MPItrampoline.v5.5.1.i686-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "d846631d5a2adb82165b7fa2ae225e9ec927547d"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "9fb55887483dcee9ff032518fe317d50ea0e74d0730ea0882fad52071f02ce9d"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+1/MPItrampoline.v5.5.1.i686-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "862c63be526eb857db8f2f4106964b2fcd2f5fd0"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "276065bd7e731e477a039fb9846ee347ed0da5dff552177fc596413a16b8e3e5"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+1/MPItrampoline.v5.5.1.powerpc64le-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "8090c58ffb317edbfce9f612b8da753f1a1f09e0"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "d4065e5fc60e64411b10ed8fd7f8ec060d9e9dc105029e50a79e0a8d25f29e56"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+1/MPItrampoline.v5.5.1.powerpc64le-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "4f3547f6e393bee5aaad9b8a670fce6bd0ff8a3c"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "1b4a9bd7ade4a66457e0b37f8bd5d598cc0baf119f983ab6e536f37a8974132b"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+1/MPItrampoline.v5.5.1.powerpc64le-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "riscv64"
git-tree-sha1 = "4aa9a8a2b1c73521e66a4993995190b24814fd79"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "567d1cb9b1c84d373713664c0f2a5da2a6c0dd2c1512d74e81d0e00a11c9c6c3"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+1/MPItrampoline.v5.5.1.riscv64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "3a1736f7454dcbc44e23f4fc6830b7bd22f6463e"
lazy = true
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "296981434f86163c982be96365ec3a3a7de1dad4bc2e71f400291d6429d9c4b2"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+1/MPItrampoline.v5.5.1.x86_64-apple-darwin-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "e761d3276d7905f43468ef4d0bd242d58878aa49"
lazy = true
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "3df81e0b9b93b0a8d5b851b92ad09660d402dd3666b4b8408c7fc0dd363202f4"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+1/MPItrampoline.v5.5.1.x86_64-apple-darwin-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "71c74ce094cdd3fe7e499de5390cbb2593514bb5"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "d87157ef4e65be5ef3cbdcac840ee3b356fa70a696bf543209b3191e9a25e937"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+1/MPItrampoline.v5.5.1.x86_64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "e73bb93d8083c27d3a12a3e5ae0564baca6a2491"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "bbae30b01bade5b5f9ad93c35eb5ecb85b66bca56add6530209245569c5d16a3"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+1/MPItrampoline.v5.5.1.x86_64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "0619513244748f3b6f61bfcf887178843ccb4982"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "78c7124361780a6b1d4e1593da0edabb8b355fff3d6263cd802c5245737491a6"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+1/MPItrampoline.v5.5.1.x86_64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "cb9a407ccf1586d5fb43b5278682375f74dff012"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "301ca1cf00c222e985e99606bd0e3968c7ddf0168bca8dc211b54e89256d3546"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+1/MPItrampoline.v5.5.1.x86_64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "8d0cdaacca88968d1737f86c908631daf5213c32"
lazy = true
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "freebsd"

    [[MPItrampoline.download]]
    sha256 = "5209e4ac7976a5d6d9629d6bd86b314fa35bd22b7e1d75be0dd1939d5656e343"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+1/MPItrampoline.v5.5.1.x86_64-unknown-freebsd-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "ca52c24247032a5208bf542f843e45d9a27ac6a3"
lazy = true
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "freebsd"

    [[MPItrampoline.download]]
    sha256 = "81f897c198603a5335e7a117d9d878839e34a731603d591e9e48301d23b618eb"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+1/MPItrampoline.v5.5.1.x86_64-unknown-freebsd-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "afca6ccfcb566edd214e500fd3932aec35f3c424"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "freebsd"

    [[MPItrampoline.download]]
    sha256 = "29b6325d2b5141f6af08d35a2b8d452249ab829fc89aa7720c81ef22429b91bf"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.1+1/MPItrampoline.v5.5.1.x86_64-unknown-freebsd-libgfortran5-mpi+mpitrampoline.tar.gz"
