[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "f91f1245e82d2bbdfc3998f8394df32c27c1f85d"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "b1456a80568fcc09933f1af624554b5f0b260acca92ad99ad05a8244c743081e"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.3+0/MPItrampoline.v5.2.3.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "068a00bc553f57f1e614167fd35535dc8f2f9e12"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "793ccbfd8ad5d5188a19b98a1c6355adb8c5e9b0bc5e9de3070c86865be70cde"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.3+0/MPItrampoline.v5.2.3.aarch64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "50187011ad294523ad14da0410986de2bcad3925"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "e90d76a4f50dcaa067880c98daf18966a3330fe165e51f823db61b45e217e17d"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.3+0/MPItrampoline.v5.2.3.aarch64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "53b2d9d8a01d9cdd54f9a8b7949d9981ed5c3d3d"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "00fd20e467737be7e3ddd0d25c866ebeb597f8d21fd1d03cf95f22655e8fc1cd"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.3+0/MPItrampoline.v5.2.3.aarch64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0b70ad82273e3a9daee3cf8b7e50d66824e7cb4a"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "eb74907f78fed201ba1cb4c58c3c714976a4a7328715effce47a18ea13992f92"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.3+0/MPItrampoline.v5.2.3.armv6l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e84ed66ae85ccfa766cbcd8b5d4db1552f103f22"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "a78cd8ea0c308406d8f2c0ac8a89727eaca1a03ffdde80e426ae735779e5a522"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.3+0/MPItrampoline.v5.2.3.armv6l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7664a683e3258dfde485ed0cd347245f7917c36b"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "acb179f1d357849fd6fc5eacb4f268d2668320110ba7b4a6f32ca49ca68ad752"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.3+0/MPItrampoline.v5.2.3.armv6l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9956d70cc71ee61f0ff610edd09f980b29362dc8"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "df33fecff94928aa89d8f024cb5a6cb1c7832b7fba8dc19138fd8be209c87538"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.3+0/MPItrampoline.v5.2.3.armv7l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8cf3354db0e091d4d209b3381891b36a65a5d1ca"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "2976a542ec94a24048c9c9c3784fe9bc7ffff8d39447c9b8fb8329be3f525904"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.3+0/MPItrampoline.v5.2.3.armv7l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "81b252d8fcc01f5ceecd4dfc3600a4fd38146850"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "1b910bc95c9cddb44c91ef8a3f35c90a6c28278f9d947c75e90bd8b52146121d"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.3+0/MPItrampoline.v5.2.3.armv7l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "db86331a5fdce231d6df0cb59f4589ab5e3435b6"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "b435a5f7f1ab79a98fe3e2bd7abce29b5ac4436e32254f9c15928b93b68c3d57"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.3+0/MPItrampoline.v5.2.3.i686-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "9962b2f241956b1b1f595f6196dd450b5a05aafc"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "b40c1fdc8bf1af27aa811170a3242f88cf456d13dba5fd5d66a9e60e7d84d529"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.3+0/MPItrampoline.v5.2.3.i686-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "7a5779a6d6201491141d4e346160a3e7cd177cbc"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "dd877624445f032f3506244b2c2da97743b0f9f2aea10bcda119059c26e76ce5"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.3+0/MPItrampoline.v5.2.3.i686-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "6a8dbf6d884afedeafa50c3b247449abf2640255"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "46721069306afd0e67e19bfcafd4d2bae28ad8be425ef61831fac1d111c5f65f"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.3+0/MPItrampoline.v5.2.3.powerpc64le-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "1fa6ccd8119ba30a0ecf4fede7e0ff8295897917"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "477b5ef6cb8727c9746ef78da15dd8124af5f77d99a5f1f5e76e0bc389c86351"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.3+0/MPItrampoline.v5.2.3.powerpc64le-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "45c8c0fcf9aae72b06413ebf47db9a332cfbfd9d"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "b3d4ca6706cb58df498766d64f2fe886b37c8857e9077e9ce4c5f4396109b14c"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.3+0/MPItrampoline.v5.2.3.powerpc64le-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "af8e6bb715e915d7db765e087d308d8331fb8f3b"
lazy = true
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "eb78a2a312eb88394f7b29080b8d2bf393eba1894009ed470ec3f3f0eda0d503"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.3+0/MPItrampoline.v5.2.3.x86_64-apple-darwin-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "768166aa8169eba6364ba6b5be00313b4931148d"
lazy = true
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "b8e753245d91c1271f9acdbe17281ad5bf7b1a039441ba7699fdd5ecb69f4717"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.3+0/MPItrampoline.v5.2.3.x86_64-apple-darwin-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "513d58cdc892f4620d22ab301be6b75473ec6bf1"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "31f3ecef45c207e47c45b4767a99b2a5b137c612f3ba7a5e8482435e78271dd8"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.3+0/MPItrampoline.v5.2.3.x86_64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "50ebf04badbe7cdc9741553e28e47e14e3290311"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "91d003b51a83d40492b74837acebea7debcdfdce4c3383d10f170e86f5ba659d"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.3+0/MPItrampoline.v5.2.3.x86_64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "4a68df228fc43b7c2e1d9b298aadd0499b2603d2"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "80c19c34f412a6b231f8e74ed73adf507cb2fa49eff4e600deb09855ada12d9a"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.3+0/MPItrampoline.v5.2.3.x86_64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "32faa75dd4e35696e73035a5461d310b20973f43"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "e124bc855251295125dbcc78ddb16c438f5f6d0be7205fcc0974726f9a7049bc"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.3+0/MPItrampoline.v5.2.3.x86_64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
