[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "e9b86a084a39de1ea6acfd76f2bebfcfe16c62cc"
libgfortran_version = "5.0.0"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "9f4d5f9e9520fd841b5e2b08a5b1d9d09419837613f2a3a5ba56dfed5b2e78ae"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+0/MPItrampoline.v2.8.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "8f3eeb4c9510af132c88cdad26e2c207ae6d2a56"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "c7297bfc1506bcad3c9b45849184acbea43b3d249eef6cb676ca39e0982b82b1"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+0/MPItrampoline.v2.8.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "73e203a8031ea46314cedadeacf71e6945361e8e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "6a28ccb0e0d1edccaf6c677dd375de32a4b36023e68fc44a3ecca9ccd1d8f18d"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+0/MPItrampoline.v2.8.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "23c6f4027f692c0cfe0c0504d520c3cf10f34599"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "0830b146f7688401162b2bcc9a9fa2322bea72382d526207d8ea24ff7f9ed3bd"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+0/MPItrampoline.v2.8.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "028ebe9d62ca606d476ad7608e1db445ae63def0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "09710ee28669cc5b0af032d6956abd6e8e9539f5fd680d647c87d4ba9a57a4c0"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+0/MPItrampoline.v2.8.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "11d596de425bd97aa11bc968fb694d93b363058e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "840493e80ba1bcd504423bed7446d6d2a82acda81464a8d31d5eac119567c869"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+0/MPItrampoline.v2.8.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "249379b3ac4e2ad7d223e7244734b6a5265050ed"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "dda4ee162286c4edaf9856d793cc3ea784044067531c7bc015d28940f915b0be"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+0/MPItrampoline.v2.8.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "5aab9e7fc90b9a56e6c2c1465ac67e0640638d90"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "bb5df24ae8db6453e34e75bbbfaf904be53603e77386c28bf07b1e153ac6da49"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+0/MPItrampoline.v2.8.0.i686-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "674ca318b6bae062e4ea7a969250a96b4b1005bb"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "f1952953b10f6a81f0c356d14f11d5366dffc63240f1aa993ec67b82b8324bf1"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+0/MPItrampoline.v2.8.0.i686-linux-gnu-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "caf9c35d543bec53f2c6d690b37d3b223b6b205a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "834e453d8478f5e3d7681b19963180ed89558ff88a79873d3335a737930491e8"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+0/MPItrampoline.v2.8.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "67342a86d312e0450960cdb630ddf2d36492b476"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "ad760695853d4e1ebeaf1399a6956f607d477a6d5a73b800a079c59fefda1391"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+0/MPItrampoline.v2.8.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "12ae27ac5ab2a99ed150d65547cb520820abac4b"
libgfortran_version = "4.0.0"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "131631eec11aef20d84ed49b5b57afe276020f3b5c3d3c9f1aabef1c2e97df1b"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+0/MPItrampoline.v2.8.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "40d7426a490c4a39d290ad4fecdd3a05b8209510"
libgfortran_version = "5.0.0"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "caf67715b4286f8b190b3f21f6b02b382397b8d7777019eb053eb07aa44bc155"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+0/MPItrampoline.v2.8.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "92ff35601d6f693ef666836798acaea9e4e440a5"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "14a7a08e8c5c267c8e4ae9ae1048adedd247d18f5b29ba2a12fb252eb3c6d71e"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+0/MPItrampoline.v2.8.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "417bed4b7517feba997ae946944b746acf8d53f5"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "d5c18d2e5204e96a301e8099fb3f56dcd38fb095653a2798127807b20b7e36f0"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+0/MPItrampoline.v2.8.0.x86_64-linux-gnu-libgfortran5.tar.gz"
