[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "e304724b838aa2b6806c39013d013f332cb44840"
libgfortran_version = "5.0.0"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "a239776962a17b3829654c18d01ded37b35969368e63bfa8c4e213b29132cd67"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.7.0+0/MPItrampoline.v2.7.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "4aa7003f41c2d8dab4d7c7c5a780249c871a58f2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "0f144b9b9ba64515d8156d43d457aad73055d4401f4e1e99c8ec64c98f223f83"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.7.0+0/MPItrampoline.v2.7.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "9c76e28755f5d8d380ad2e99768694e590dfeb0c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "f6e60b55f4a07c4f5297cb2f12b9ef51596e266c4296735357ec1eaf2c6c9719"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.7.0+0/MPItrampoline.v2.7.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "843aa4a5882b3520bc129fe10efb2d52880d9a5c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "edf6fa95648609c34edf3ddd6df61bec0a75deb6b8993c88ae14518d36574e5c"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.7.0+0/MPItrampoline.v2.7.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7d6b6a52f2326e2952af7858c9c4e4d83b7f8530"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "aa67e0f617600d147b708dc26bd4f46228a0ca1d1a8ae26bda2e8d7a13c25524"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.7.0+0/MPItrampoline.v2.7.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6030307fc9122e0380bc0f10af8cb5cbab32f4b3"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "8f01d8677641667919d7baf41cd96fffc4b7fb35c6eea826dc02ff86948ec45d"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.7.0+0/MPItrampoline.v2.7.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9195bdc89b531270589dabe26e208c30c3b10228"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "5ae9b086a562daee781f0d471b96e3c698eb215b4c6bddeb4bf77973a23a4b4c"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.7.0+0/MPItrampoline.v2.7.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "f20bed10a18404c822c0c69d65c56f85e4c778d2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "16b8c5e685fa90aa41cb7883750aad1350feef2221b9c2ee804a4ad5356287f1"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.7.0+0/MPItrampoline.v2.7.0.i686-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "fbd19d969afd74762abc070dfbe161fee9eb775c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "4fd29ecad038dd858c72abfce35a10057d36bf3964032ce4b8aded14a75f667f"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.7.0+0/MPItrampoline.v2.7.0.i686-linux-gnu-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "2fb303575fbd49cfa863814ce96cdbf27fd37cd1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "bac3b7c54fabb66550fd4a64c60da00bfe84bcf14bcbf51f7b2945590992a581"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.7.0+0/MPItrampoline.v2.7.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "1a274bb12d5238cfef3b002b62c17db7bb3b46bc"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "f984572001b68559fa2a69512c5239b43cb303cd15999a7f86b340f07044a958"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.7.0+0/MPItrampoline.v2.7.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "6a54ca1d05210d4828382f856a85f07cfff9b4ff"
libgfortran_version = "4.0.0"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "e39237f13209ee28aee279cbbf4eba0d0daad73281b7d61e045ac627b186aaaf"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.7.0+0/MPItrampoline.v2.7.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "aa58f2a16a53d0c5b64893f4bff0b0139b869058"
libgfortran_version = "5.0.0"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "a58127c3c19cef5b9d74c614ee943fa6153297c16536a0504788eef190424ada"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.7.0+0/MPItrampoline.v2.7.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "7bcf5d06341ac183cf339023dd498d18ce225385"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "9ee93602b39ce98306a93b4f694ebd3048ee16651a4ceab45300c262a8699365"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.7.0+0/MPItrampoline.v2.7.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "067ac985cbcd51949589be9e97dcd55eba599b9f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "afdea14a57b74deb9e743700f4c9217c4aeda6b440b2009677ba984e3d39ea6c"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.7.0+0/MPItrampoline.v2.7.0.x86_64-linux-gnu-libgfortran5.tar.gz"
