[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "3d40baaa3f7b74b79c49a46708345db58df4c530"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "deac27ca7b9735aad95319daac20b0312a1870004a223eb1c21294879c5d377f"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.1+0/MPItrampoline.v5.0.1.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "c49cd01311c9a6ac7cd9b6858f8658c193578840"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "32563acc66f4665067cf948a0c76f1ef84569ccdf0f024474dfb3b0cdbfda0bc"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.1+0/MPItrampoline.v5.0.1.aarch64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "cafd045cec283ad8035907e9cfa401eacefd1384"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "eff3229bf9a35e440f65f14d16c60e87f18de3bd63894c9171b0b4dae6dccdea"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.1+0/MPItrampoline.v5.0.1.aarch64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "acb57918c05c5eae302817201da035c27f30c2b6"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "4dad4ba956dd2280ce121033fa2b92b32b3b7f0fe7f2281c7a7c28174b7a1ebc"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.1+0/MPItrampoline.v5.0.1.aarch64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "185834c9b12a76b24dd7f8dfd95f76e90b4dff6e"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "04fb314e83882001871d8fd257ac7bd49360d0fd789c6b0e8aa31e85889fa40d"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.1+0/MPItrampoline.v5.0.1.armv6l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "96c54a11790046d87aa1ae737ba11b749a9d46c8"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "bc23551ecee34080e19e259a9e0d6d33e66ffe7025a31bc109ef383ac78d0d77"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.1+0/MPItrampoline.v5.0.1.armv6l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0426ab575df218e24a027a9d5fc364bec3648cc2"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "5c2cb5be7deaeeb2f7f0bc4ff6a4d13f966c8f51db09f0ebdadaeee558a7ae94"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.1+0/MPItrampoline.v5.0.1.armv6l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "48770373705940dccda2b5921be41d881cab1693"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "322a0591516d1ba445f6ed6cfd92116ccf46ecbf962402b966424afcc006bb7b"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.1+0/MPItrampoline.v5.0.1.armv7l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "72590a863596a0b8169ab8772bda351db080ec43"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "70a13605e665a72daaadc01b47b0b688705e30025484e85e7be2021c217dd45c"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.1+0/MPItrampoline.v5.0.1.armv7l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dd866a061777f874f7c68ad0400ec92c56d4d73d"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "66b84c313e861dd6c3e62019e4f54f0b82f2d7f9168a655b1b81a643ef6bf19d"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.1+0/MPItrampoline.v5.0.1.armv7l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "8ce745929d66cae2523f673b0050395cb9e71714"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "8ffea53ca62c36213bba1e4e1d2f381743528f7360d605363f143b1877de238f"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.1+0/MPItrampoline.v5.0.1.i686-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "3f66e6fe988591a188a4f9724f01048d93d35985"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "a44f8355bb0811f5cb900d2d72fe14b019a24453db84f73cf17e40e2ac89d391"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.1+0/MPItrampoline.v5.0.1.i686-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "e6996c21e4811607d8cddc2331df999c76998ff7"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "2279ed7a7e25dd9b5e1793c9615e4229c152bdd35ed00484fdc655797dba80dc"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.1+0/MPItrampoline.v5.0.1.i686-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "e535c5619063d3f7e735537583929a0a3acbacd7"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "ec3548ddc22fd9ff3b70d7a4dc8a39ef06e56d2a53cbf9c12acd176346ba94fe"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.1+0/MPItrampoline.v5.0.1.powerpc64le-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "debe61c240f6468c60739be4430fc1c1a01676ad"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "b425a09fac07d43f18b3447e7d28a0af4bda14b3eca2d0ea761ad8b706316119"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.1+0/MPItrampoline.v5.0.1.powerpc64le-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "6ac430f1757fb7548d143364dae40935e2cae53f"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "a3739bb063b994855629223af5637aeee247e8eed2b5fbdf53384b4f86ad6485"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.1+0/MPItrampoline.v5.0.1.powerpc64le-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "a6ebf6f4a36ece475b73ed0a876a6f948487fb97"
lazy = true
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "6ad2255a498ed5c07f08a25dbfe07e7e9fa2bc3a937230d940479dd0e71c5cb9"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.1+0/MPItrampoline.v5.0.1.x86_64-apple-darwin-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "9ac3848bdee790f811c83ac4a4be741e5d4cba71"
lazy = true
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "9c3566703063940619ece10c3ab2e2093bbf1410f4ea36063b3d282a8d74c7f8"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.1+0/MPItrampoline.v5.0.1.x86_64-apple-darwin-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "7b10f4fd0c12e8818c02288563d63e6fed4488ac"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "9fc15278265e32885f77ec4f0f87ac5e8bfca1ef7e643229c68d3c93ac4e844f"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.1+0/MPItrampoline.v5.0.1.x86_64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "ea565c306bd8cb172bd8781cebbbebcae6f0d368"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "44172a39e64f23281b8da2d836aad357c8a1a8f230e0f344c94bd58f15ec99b3"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.1+0/MPItrampoline.v5.0.1.x86_64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "80c265ea865ba126fdd70aeef327b8ae786bdb48"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "bdad1b302b2b74e774199231d2ec39bfa9a8ca46ec8498ba127ee66099f3e890"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.1+0/MPItrampoline.v5.0.1.x86_64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "63eb3ba82a47be6b856dd8717dea61e3e7b33436"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "e95f49e450813e04f28b3d13a57b63fdb7e7122d0163337d2f1b68501e9523c3"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.1+0/MPItrampoline.v5.0.1.x86_64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
