[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "811e7b6cfd1d75ada8b8c2fa943b72c3a0cd8685"
libgfortran_version = "5.0.0"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "4f56a05744189f897983375454a223d8cb34fda7247a88eafc68642e167743ea"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+0/MPItrampoline.v4.0.2.aarch64-apple-darwin-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "704fddcf26a2e12663bfa273b88b7b2b857a209b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "abe96dc7ba7a1392d765e5d5d40311087b2f0d64cf872c30efd014944d561376"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+0/MPItrampoline.v4.0.2.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "9ae2d0f492ef81d87899425dea7a2849acf24bac"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "3569622eac1be653607fa37c7e7ab7cb78900e81789ea443b1b64d65371509e2"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+0/MPItrampoline.v4.0.2.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3bd318c8074703569c3aaa84c83f1fa5d65c466d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "b477c44b8094282dc359d85ab5a4065bfaf55c38d9e125535d66cc9360d7588e"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+0/MPItrampoline.v4.0.2.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2e30bc8f001aaf0c59d64c91c37298880b469571"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "8532f48276830899a22d73c4eba53e1a22cfea765d60342e8cf5f6c84da87705"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+0/MPItrampoline.v4.0.2.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0e59fe242b07f1364e80d7026c95e9bc84ca7e7d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "2f86ae5ec749a82e97352711066a1138d5d7f0a060fee251a019979b3195340f"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+0/MPItrampoline.v4.0.2.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9ca0318ef0926f972ab587420016cca1f6bda0d3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "d8d2ba610b2fedc46d754a2dde599f8f5ae9d527936af4bd81888c26c53f5d75"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+0/MPItrampoline.v4.0.2.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "d62bf999a2cef6af59fc2c45ddfb8761859d967b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "dc22837504c32360fd78266583291b9bbb991264e3ac8bdab6fc17d7504bb3c9"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+0/MPItrampoline.v4.0.2.i686-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "32e2c9706481a274d6046e390c8cd442cc34853a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "b4cc6b174aadcbb30f2fc4bfc80ea80993e7d32e44eaacea706ed0add2d47110"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+0/MPItrampoline.v4.0.2.i686-linux-gnu-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "f2dd0cef3501dc7cd55e35c3872949db716f2b69"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "a6e8b6fd2a7568380e7ab13dc6ae206a9ea0eb8b3155e313b6772ad8f68da0c9"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+0/MPItrampoline.v4.0.2.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "91990abf6127e564a4253498d5c1eaa0124555da"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "7ea5b38fe25e1ed86d0317a08116b48dd667757a1a02c4489016dabb2606d175"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+0/MPItrampoline.v4.0.2.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "4c55f836e28bed7041e7cfac133adc935622a421"
libgfortran_version = "4.0.0"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "9ef060fa8e0c0f1240cabc80daea256dc03a68086b144c63aead21725c12487a"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+0/MPItrampoline.v4.0.2.x86_64-apple-darwin-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "535f3edd86873b4bd29882b1ee0e7245b0b1c0f0"
libgfortran_version = "5.0.0"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "7fb42ef53bd2c3c877666e466fc540c4940c842057b22bc9f4437a0b3d2ff88c"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+0/MPItrampoline.v4.0.2.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "a7fd54f04ff223addd993b0d07b7e4262777d2d5"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "fb694761d52a05c7787ec5344b87b5fb6e9718f4a5cc16b8a43f08e313388376"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+0/MPItrampoline.v4.0.2.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "8ed84d9205e28dfb15e00d7da3017fe387eee077"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "2478cd5dae81cf7e70861c4c3fd55f0221a045fb919d4dc22a1ca0420df10335"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+0/MPItrampoline.v4.0.2.x86_64-linux-gnu-libgfortran5.tar.gz"
