[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "ba2c9bac1ab88936506e54fa7e3e690b2f0c4404"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "20fd3f0225d9f80f98a660b97c9b0fbcb782248e8462b137a29010131a0e9175"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.2.0+0/MPItrampoline.v4.2.0.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "62809db834ba796ff52a55a456107e2d8b3ddfc8"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "d8e0518ed4a8bbed680e52e714e7d4408b07abbf9eec476c4c7637492ecdf0df"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.2.0+0/MPItrampoline.v4.2.0.aarch64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "630c6a0aa94f501b2621cc752e715ee7794ac542"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "c20659e5c4552c9be45a900a5981e3397cb5fc7b673a49658a66a23d427a64a0"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.2.0+0/MPItrampoline.v4.2.0.aarch64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "6ef4c8cfcd8d81c412407d065147a28061397858"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "3397e2880ed7073e591621fb24ab7665222bad9be4da6f1fb02a5ade09b57ea0"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.2.0+0/MPItrampoline.v4.2.0.aarch64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6c66329a345637e5e13d227c136325ee708241ae"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "4f97f916e0526af84aaab11f1b9c64f76090764e529ecaee05a9e219f65f520a"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.2.0+0/MPItrampoline.v4.2.0.armv6l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5155c815d7d06f1fe67d038da68abc4c0e7e4551"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "187b4ed8c3a40a0ecb9a08730d91c2e7fd8ab892ceafb8e10d88707c6697bd58"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.2.0+0/MPItrampoline.v4.2.0.armv6l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f7a9d64fec7d7647a0a47e4669f8338eb7a5d1de"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "79b252be989828b24cca918792b048cfa5183269f17f170975485f99c054326f"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.2.0+0/MPItrampoline.v4.2.0.armv6l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9ae3ba17fe3b6ed2145e2b230136fd9f0e18831a"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "f765d570ff5e2b166fc8fec4f6b26fcf3538567c758f27c1d0553faf476c7eaf"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.2.0+0/MPItrampoline.v4.2.0.armv7l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0c2600b6f8877db43345efbc70cecb1ff75f6800"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "ed84eb864799ca8b48457d9472840ee336e50c4ab05e49799df7fdea01ede395"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.2.0+0/MPItrampoline.v4.2.0.armv7l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ff2251f73d5df3b4d2a33010e58bf84c1cfbde0a"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "5d70dd604d0479f766c58f8def4dadb27844913b9a487a3f060cfabae4a0d604"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.2.0+0/MPItrampoline.v4.2.0.armv7l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "94820266a51dd92cd6d78fe2759fcc2bb0229733"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "4c5944de120052a7d185f69597ff56b1dc2f4d1c804030168411334081b0f281"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.2.0+0/MPItrampoline.v4.2.0.i686-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "fa24a211e9b00ab1036f79db7e2743b869e5e9ae"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "74d3fca026aa7798490ec11d0fd1d9398e3fb33bbe70c80555dae3e308de2525"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.2.0+0/MPItrampoline.v4.2.0.i686-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "a1a22b239894f379230adab6740aa6e896c0c808"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "0547264aa5a0e13df440a3227b61210ce0bc9bf0f17fed75f97fd48d46e651c0"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.2.0+0/MPItrampoline.v4.2.0.i686-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "a85d262861cad65595a29b2eae973a90d976600a"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "280c76a412c3e310c6c157f74a738e413553c1d59e8b93101be221a29c46e392"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.2.0+0/MPItrampoline.v4.2.0.powerpc64le-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "d257b93e1916b0bddccaf6f6f71f9ee7971d1391"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "22155cdab7de2b83bd16c9e015f27e2b3f9a56fd9e5d6b14a8bbe2fce1da115b"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.2.0+0/MPItrampoline.v4.2.0.powerpc64le-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "c362d431cd96bdc199592b0602744e86640167ef"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "196259dce53ba2b26f5057d8fcceb43ff1c7d3834329212b8616eedd31ab687b"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.2.0+0/MPItrampoline.v4.2.0.powerpc64le-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "0b76496d891886b2501067f94c7cfc52087620da"
lazy = true
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "f622d72834cc278e18fe0030530c6c2aa7c44bcd12c44939c9869608118dedf9"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.2.0+0/MPItrampoline.v4.2.0.x86_64-apple-darwin-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "6744bb8339b4b97bc5348433250183f4921e452e"
lazy = true
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "17e3b8f473b09fc13f35b83ad233ba6c0c6e82ce9c3fe96b6a1c8c0c1423bc24"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.2.0+0/MPItrampoline.v4.2.0.x86_64-apple-darwin-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "1d32451b27520c8f1ea26ce1c2f06564e6a1381b"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "7876502dc70485c44c701434ba04ec87477e3ff66d4586201d75daff3a07e2dc"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.2.0+0/MPItrampoline.v4.2.0.x86_64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "a5ecd2fab29619bd237c5fbc9e509573271def64"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "604274a39fe354844d3a760ed9e084716487d3d2ff74df008cf3bdcbc4f9d41d"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.2.0+0/MPItrampoline.v4.2.0.x86_64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "e01469c5748fe3325a9abe8ee743db8f2b5c3bc9"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "d7b1a33e5225d3154ed93c93de6a8beea06cc6bff67aa1d0f392cecf171a254e"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.2.0+0/MPItrampoline.v4.2.0.x86_64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "50f787b5e95baae62d5909c8d003b9d65f2f1c54"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "745c2ffe1f73366cf52a8689a1fc888f0789e419491897e1f42f08a7ce2868d7"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.2.0+0/MPItrampoline.v4.2.0.x86_64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
