[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "923b9a774c65353c293248a2081d1cceb1249319"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "c751a7aee938de1d4a88a85b5c3b9b928a21f5b54dbca089e09511775570e58f"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+0/MPItrampoline.v5.0.2.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "ee0c6f06a3d7eb338c48e6c316efbfd94af22cda"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "695a8bfd57803193c87f3d5a267ccb3724d2b8642e7302299ae6187328299c7b"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+0/MPItrampoline.v5.0.2.aarch64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "6b938351892f3bc86d54dcf98880b1ca86404564"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "b5dba9d22614378e0f36ff2142935e3b5be232b9e9738525ec450aee47a81320"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+0/MPItrampoline.v5.0.2.aarch64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "0bfc031ddbdfd78a18b2538a7d1c45200918984b"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "af3bed00b550469c513560e0915c8633e3bc33421dc252aff0f670f24f5d0f82"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+0/MPItrampoline.v5.0.2.aarch64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "852e8e8ec2bf8da6c67aa4ddf7433757442c382b"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "caed761c0eb37a8fa7e4054efda758df107844fb60fb69089885049fdb6a2b22"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+0/MPItrampoline.v5.0.2.armv6l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5545d329dc1d1b03d5452dd64ce62b05b1ae52e9"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "56be5aae12049f30c7a31921ffa9d384f58a413d5bd33a38087cc58d7dd30074"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+0/MPItrampoline.v5.0.2.armv6l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3f108ca2ee32ab6f638f548ba5deca0bd36d55a8"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "6de59717f9e8f3b82f91402bfb7f90527f983763d833ed5c5a952d9b403f8c46"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+0/MPItrampoline.v5.0.2.armv6l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "996c74d2553a2e91a7fdcf3723fd02d428e0ffb3"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "ed861125d416d61ef65bee236f5d3349f7a1ade2e33e24f73093aa8733633716"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+0/MPItrampoline.v5.0.2.armv7l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "055f18a76330551d29f411736a161b7fe0363803"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "f65fbf7c80a40df3e148edb613577c121f64666cda84334144be8519afa17d57"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+0/MPItrampoline.v5.0.2.armv7l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1095cb33d8db72dbe2c4c770bbce71912c159fda"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "1614a95534f978580c8a251a8c779fb9c1d88176efe2c35255c609c261ef9624"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+0/MPItrampoline.v5.0.2.armv7l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "5b97873d651195fd143faf16735742705a816dac"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "1ff63e173526fa455bc06d5a97e0cb31b0916134e524de817526326ab4faae72"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+0/MPItrampoline.v5.0.2.i686-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "aa09ca63f4f743247dca1e80d668805ed1b54e30"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "64ce0ebb86f016cf26d511b153011762da132deb152ccc43ae2ac0360ab5d31f"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+0/MPItrampoline.v5.0.2.i686-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "966565f8483471869082ede6e625017cad3eb32c"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "0c80f96cb1e9554c61725d8c904eef3854fd3875dc6d2e25ec8f99b773631651"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+0/MPItrampoline.v5.0.2.i686-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "f1e6f5ac593d03cf04e800237a7631585aebc039"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "848031b6b5cf1ff646d5ae2ff16aff7a33f145686d979796cf21a2ff6c2289aa"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+0/MPItrampoline.v5.0.2.powerpc64le-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "4886fc47388f1551824530e968225104a860c44e"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "b2781e571c16801106e478149dc25834916f05449faae0c0620b82e92b65097a"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+0/MPItrampoline.v5.0.2.powerpc64le-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "966b4baedd90deb359bd5aab6a89a1b029dd35ac"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "19a6b10d7552b6aadce8ed2ee309ec90220e44b2150dd8ce682117fd94051eb7"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+0/MPItrampoline.v5.0.2.powerpc64le-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "a16b47b933309e1e92fc2f7d64bedf64cce2bed6"
lazy = true
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "09c42439eeebeb13d21fa37428819a6357a440c945536c2002195ae72417848d"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+0/MPItrampoline.v5.0.2.x86_64-apple-darwin-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "1d5907a8f91d2041eb610e8774410d2aa87e4246"
lazy = true
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "9601bc9bcb271d5331c82f3f210668e48fd73453fa5e971bd45120ce4ae914b4"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+0/MPItrampoline.v5.0.2.x86_64-apple-darwin-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "d05bc5f6bd57459f177f8b2b7661e51ccb7484ea"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "a00e0f3daa1da22588acfe39655e75999dac636e66992a00dcbe7f7103beae45"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+0/MPItrampoline.v5.0.2.x86_64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "c4fea39fb83beaf316833e4de48b31b95f632c94"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "d2105ed10772edd9a153ceb2eb3ec669d4cfbab9d23b8473b3951df72e6afe6b"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+0/MPItrampoline.v5.0.2.x86_64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "dbee6897716c7470b3a319036e9a96f2a60f7f97"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "bec8171eecc080024f894e92c7f6ee5dbeafb0d654319e9c0b6f371589296fe3"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+0/MPItrampoline.v5.0.2.x86_64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "efbb79bfb19974a0efc9fe38a129b386ee7f0b38"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "9005bae09dd2af7d4e034ba1bf9920ddb18bed2e44991069b943f91244641826"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+0/MPItrampoline.v5.0.2.x86_64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
