[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "27fa27d38e4b109a8e5aec769d9d7c3f8959059b"
libgfortran_version = "5.0.0"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "7e6620ec87f8463121888750146a7fbfd856f1969bf45373960c8902fdedc47e"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+2/MPItrampoline.v2.8.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "47ea80d29bb8723908ad36ab304fbd86335dc7e9"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "029f2100df50741c2a9c9afa2d0af4715a4a21eb90d02a3f10612ec3f7c91782"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+2/MPItrampoline.v2.8.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "71e87abc98383cd6166f3033b1eb4d1f89c1dbc2"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "a54d0f62de684564ff7374a76d6ca48b1487787837acf9b4c7e1ae471411009a"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+2/MPItrampoline.v2.8.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "728513b56d597943106ca719f8e957781d22b427"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "57feed2e3d1f1cd3e2446e1b911ebbab7821b6a7f48ef775fb6f48c97d51b1d4"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+2/MPItrampoline.v2.8.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "78808b0f8706ae4c3f124eefcd8dbc3dfb5ab3b6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "91201df3516ed0f37d01e59e9e89c88782b0a00e6fbecb65d6396082b203d8eb"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+2/MPItrampoline.v2.8.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cb260d4c15d4e15d2d72abb17167397e6b494f8d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "7734f6ea61970e4a3d21a2eb773f843582d82b6eec4fe377778e0115d38bd261"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+2/MPItrampoline.v2.8.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4a2bc0dd615fd3916227a53fbde3fad5ca291290"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "7baae2972c6512225376f6fe8337ac48700dd9eb9b16d5c8f6a517ccd2032306"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+2/MPItrampoline.v2.8.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "a81d5a2b5f861caeb8c841b0c7a8a07df639a254"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "d0865683cc7159369435471543e70990b54c191105443abd3b0634235e9da404"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+2/MPItrampoline.v2.8.0.i686-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "77cddcc3209d8f076469ab0848e998ecaa653f8e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "48642d619f4da07118cc079abe2c3f00d501171710bf406e4e22177c0a2401b2"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+2/MPItrampoline.v2.8.0.i686-linux-gnu-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "56f85f0c2fbab6f9f4e3bcf0ea7b2c7ec5cb5d37"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "44cd358d77befedd1d66bcada1a47f63b8e1f56324f24e18fc71cb47eac1db59"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+2/MPItrampoline.v2.8.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "c6078569a5f04984c0bcf6c3708c81e4762bd090"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "0d741d5e6cab919d28f6fe12ed4628d4e700ddaf7059c7d71afb02c1468a785f"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+2/MPItrampoline.v2.8.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "526be95f60eeb20280339e372def465b6c275c86"
libgfortran_version = "4.0.0"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "ec12bb684658d862cc798f73621f605dda337e30343e9b3b279e8ff52830685a"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+2/MPItrampoline.v2.8.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "edb5bab6e0428e2bd8fcc9a4d20f732d38bf451b"
libgfortran_version = "5.0.0"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "d4a17956399d05c17cdecaee597d8a3e1f7dae085054b472c38717deaf2a1a68"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+2/MPItrampoline.v2.8.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "7d7b1ed01a1617a71dbd37f8efb302886729a8f1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "f8c930428a49d29b7e4c6a62b1c52968476d0c813a7c154005eb9318ab21b863"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+2/MPItrampoline.v2.8.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "1bd100b9a6a800da141c1fa880b5c2f33c9aedcd"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "2aa5ace5106238c20c3cc47a7a6ee8d8757d4e2e48543fb2aee54c4c22adae4b"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+2/MPItrampoline.v2.8.0.x86_64-linux-gnu-libgfortran5.tar.gz"
