[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "b6116717ab2fdcb9f61fbb862b1b21ace96eff09"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "60a2bf94d0638399c0725ea180c39667de2fab0d8cc5b8a04cddc3e655789eec"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.1+0/MPItrampoline.v4.1.1.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "974db420e8dc30b7dc677a45c5c04a30e16dfa14"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "15655b4170ce955acbd07b2ae8b345949e8a7b41392ade03c164bcf9f2759ce0"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.1+0/MPItrampoline.v4.1.1.aarch64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "4a3a7c96239dbfa57883fa75d3a8178ef70bbbd9"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "2a04e23a6b41f69cf839cca5e00d921f0d03dbfce47653fad53ddec75af38333"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.1+0/MPItrampoline.v4.1.1.aarch64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "85399b8b1063b7f72f68fd748364a4e8826ec9df"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "f19b42e215959a0ca178ccd8709030f7871f8d45b1c9a9b4e95f34a6e32f8218"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.1+0/MPItrampoline.v4.1.1.aarch64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "383f185b366658d9e953a8fd5a93eb4a640f818e"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "8ee5831ee07bb5dbcd81a6f4ffc1f887ba1b43f801067db1e6c0b90926104cc9"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.1+0/MPItrampoline.v4.1.1.armv6l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "010cf1e519d0f6165eae0f8ddaf4eb03de205739"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "40dbf149e9b8f00a7a9c75eb728752f41ae01917b41a77dfb940d9ddb6095be9"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.1+0/MPItrampoline.v4.1.1.armv6l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "14730edc32b8c0d63069f19d936b2c1cbc4159a8"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "63d9bb7d4353e16cd32b876cbbba3720b0d83459fa6411715371a0befe04ffae"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.1+0/MPItrampoline.v4.1.1.armv6l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "99ce44ed5cab3d744e0159581b4690a44807b087"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "a1b3fc6fb8deb484148c4c907bbca16852dd5bd76285d091b9648627bdf158dc"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.1+0/MPItrampoline.v4.1.1.armv7l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "50d788e3eef6ed52a3069619c71a4e94762bef99"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "d6d06023c779aa306f22249e9d14a2a965df5b39971904882c5d49a9d6d18668"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.1+0/MPItrampoline.v4.1.1.armv7l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1415c9633edbab1c6c796614bae1b04df050684a"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "4c775911be9b3b79bee2b71b8462df72db89778b11249ef3e7de42fb393cd41e"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.1+0/MPItrampoline.v4.1.1.armv7l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "4becf9df9044b27079f498cb8a57125677372459"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "c39a4a3f3f2e4a916838235925af14f7bb866503984a5d568729fd99e25f572b"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.1+0/MPItrampoline.v4.1.1.i686-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "d4af751d380bb4e265cafe296c95643529b24247"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "767b066b9d2d297d7c8a56e0b734d0b205235a5d5df3657d86c8ec9702e28f83"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.1+0/MPItrampoline.v4.1.1.i686-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "9a2a08bf7a0ecf2695d654cc6d901f9d4259e301"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "a098f00a23de969e73100a677c94ff912ae4e89f1efe6e0a87a6d3264e6a1385"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.1+0/MPItrampoline.v4.1.1.i686-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "572798a0ab753fa3a26403f61336255b390422aa"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "7ace8385d8e6bf7413e245112e4046727855ffc7f70b37003f0c6ae566c9d034"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.1+0/MPItrampoline.v4.1.1.powerpc64le-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "9071cfcd9855296076a8ea9dedf6eafb304f13c4"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "33bd36c7388c695a993abd109c422b1af04fd3b44d11b51212f8e15e640fa963"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.1+0/MPItrampoline.v4.1.1.powerpc64le-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "5372292cc7fa32d34f2c009b611615f5f70861f4"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "c2d2d9a2e207bc134f7db02971d4e6ef1380438893a7786fc71b0e90a184799e"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.1+0/MPItrampoline.v4.1.1.powerpc64le-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "0cd129e259445647d7aa669c1bd54cc9d8d9a6f1"
lazy = true
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "a4b6063ba60849e1ff22ea2db8b52b5909daa07fbbfa4db8ef2395dc2070e3ab"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.1+0/MPItrampoline.v4.1.1.x86_64-apple-darwin-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "fd70c59894599b97b2fc2dc351c4e4f31b05edd5"
lazy = true
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "31f60f8b5668792626f7fbbaf5467dde49354ecee3a745befdd94939b31e73db"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.1+0/MPItrampoline.v4.1.1.x86_64-apple-darwin-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "405c584699858580aedaa2390dcc90e3453af6ec"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "570657725f76d2aab9e9ebee8e59076c84aa770300fbd5b4688abe8c9eeab655"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.1+0/MPItrampoline.v4.1.1.x86_64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "d7b2faad5cdfb8f9f59205f2acc5fd8f52a4fa0b"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "61a7e9eaf05175bfdcdd3e1567a807d8bad57cb8ff992b525ded9d5dd3bf6b1c"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.1+0/MPItrampoline.v4.1.1.x86_64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "2336d1e54757224dc91958b936e06fefd46fd7f9"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "1266f58af4d52e8e2ab04781c0cf4f09c8fe1bb352fe2e09a22005d7cfab6756"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.1+0/MPItrampoline.v4.1.1.x86_64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "e5c763008e50312067db2f8dcf2199b8e0c27554"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "554b95cf02e14aa97c8202b27a77fa84fa91e57858b6c4163c0775141e377f0b"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.1.1+0/MPItrampoline.v4.1.1.x86_64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
