[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "edad41b5c7f492193f2c70558bc445456de92885"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "014b964da9cef3e48704b8855bee3f338f58d45a0e42ad31e43b9f1695e19f8c"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+1/MPItrampoline.v5.0.2.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "7f452bdb627feff8beadb9d1eff90a53f4e64231"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "433358b76e6f08d5941177e4bcc60f496bbe5b2443859e8777357df737462a4f"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+1/MPItrampoline.v5.0.2.aarch64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "7e6913dd362f63b3df99eba8d67659cb89f170f5"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "230a429b124167c0f7622e89cdc73518a13a49b717bbd866aa6ae0ef6ef337c4"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+1/MPItrampoline.v5.0.2.aarch64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "390f6f3561f5828b97f6b44eaf455a9998b331ed"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "090de8e0b255f2c518a26ce48945fb81256d62894d9a658f4c3a3b58b4c6fc42"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+1/MPItrampoline.v5.0.2.aarch64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a0957b0cad2951cdf637414ea415df8164b49af3"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "95a23f303a92a7c7c03d252d48ffb0883d9b1247e474073a51ec22f03d3eb161"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+1/MPItrampoline.v5.0.2.armv6l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "76a9fc6b6213f2d536146a6e144a2bfd9927f459"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "c398e0db61a522fb0b76ddda529a8c0c2912fac0b16af2da5f1b8d0d54df9659"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+1/MPItrampoline.v5.0.2.armv6l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "662267ccb88250b677e54892d90103ef3bfb8a4c"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "da9543b2fa8edb6ffd860ca1cdcf46427abfddeebb5fe29c6bf2f95f0ec9c669"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+1/MPItrampoline.v5.0.2.armv6l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e04928220ee454365b523d5190697ebe6efc4db9"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "985360fa85f8a0495a64fecbba69ecdebc9005e0d3693e1e5c8fd9ae119fa9a3"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+1/MPItrampoline.v5.0.2.armv7l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7b7145811834d029d8bbe90fbaf6c9c19ddc0f97"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "255f76d1bd9562e52e3e2f203541d4664a83de1721a32994190153f5308f69ee"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+1/MPItrampoline.v5.0.2.armv7l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b14cedf0faf6e4a019827b63cd9a0144969273f8"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "7a7f1c5d84101721f098f1d095c5f2bdf6c84c86cf8dfd5ed4c7076dd2472596"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+1/MPItrampoline.v5.0.2.armv7l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "b31cfcfcb20b7d9d0538fffe65c37f1fa320a46e"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "60d27ceb8c3605fc0ca984a82bb90f36bc35d8fecf3670c3c94bd002b78d4d8b"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+1/MPItrampoline.v5.0.2.i686-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "b4de9b00d1177e38de21fee971e4721d247e64cb"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "f2562a6c1cf406b3f36b315ce007a98227ffb57bbcc7e1460e77367d8be5cd5a"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+1/MPItrampoline.v5.0.2.i686-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "8c1d9d7a4c6370daff047f827570e5a09aae705d"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "f2eabcc52929b421e7fa935f25782ef21f958aa2e22426d73d2231d3f9f8fe0a"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+1/MPItrampoline.v5.0.2.i686-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "a173533624dca8439860f943bad1482f132725be"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "551ac4ea80e71e0bc79af2426e65e812791eea512a6e5dab3959d07d950b949e"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+1/MPItrampoline.v5.0.2.powerpc64le-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "4de31fd4696c49e09f797f98e5f1597bb0b715a9"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "18a033c685fc85524f83dd2613f8e7b44115d46469fae63045ebccd0c9cf33ee"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+1/MPItrampoline.v5.0.2.powerpc64le-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "65869fe4e0e8660217e6a7513cbfe11ad0870cbb"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "941dc787b6df8098f4c7864bf95609cf19d4307ac72b9149396920d58fbe8e31"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+1/MPItrampoline.v5.0.2.powerpc64le-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "1c9e86343e3596d794538e1fdfed12c28f263e82"
lazy = true
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "d6bc137879d7228a4348b1889e54d18d15524489106d03b40c7f4b0c0fff413a"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+1/MPItrampoline.v5.0.2.x86_64-apple-darwin-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "13041af4984510184dffff7629f3be0cc9aad730"
lazy = true
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "050609721a4bdf6fe928a317340fb744cd6b7a8274a141e284ad13a3f6a6980c"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+1/MPItrampoline.v5.0.2.x86_64-apple-darwin-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "197dacd76a1c626ad6708c53fa4d5c4836cb2f29"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "296860f3d0568503d0c077d2af502c244008acbf42c3e4058aeb705bb9db7878"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+1/MPItrampoline.v5.0.2.x86_64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "fb834f4f12c804e9511448c28834853399df6ac2"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "73c6fefc8d94dc6125c319664bc746df048c8e2a5d2215feaf673041dc459c06"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+1/MPItrampoline.v5.0.2.x86_64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "95b7fa7a6ef17904e40fb7d369e2d60edc18beea"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "939916bf9867b8fff1da6a394e3a5d664a3d9213235a2b332babaf329806375f"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+1/MPItrampoline.v5.0.2.x86_64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "9a9b718b5882f895bfc48908c28c98d7306d3626"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "c30fa39b9ac192ce599a11a022564dbabf72044346b497616de52979dd25f645"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.2+1/MPItrampoline.v5.0.2.x86_64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
