[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "2f9a192e535528f59eff6a8b19835d60dac34ce0"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "ae35139b1b8f9aab72fb5f4fecc2bcac6508db9afced64692b43ebeb0087dfac"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.2+0/MPItrampoline.v5.5.2.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "a7c357fce9859c4c262499c64c0b5bc53eaac1ee"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "89ff88eeea612ef47a7f6a276ed5d3571da699edc19ab6cadb06be30f39e6c4e"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.2+0/MPItrampoline.v5.5.2.aarch64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "5854f7d9e22328c9228ef5409d819b05afd8560f"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "68a3c02b97a9467eefce66656addbd79ebbfb160f7c807390928cb5814a8f54c"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.2+0/MPItrampoline.v5.5.2.aarch64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "d49e70f1f09b78e0c8840460896d819fe8907449"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "8540c5112544cde1012acef068963ec45fc81b8762707402f830572ff25202db"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.2+0/MPItrampoline.v5.5.2.aarch64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "826afdbf1c21e7daf62e1f38b918245dc6d54e3a"
lazy = true
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "freebsd"

    [[MPItrampoline.download]]
    sha256 = "a92125aa965666d3443226d630e8e6cda2c316326ce6d9b3e600916d53c275a4"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.2+0/MPItrampoline.v5.5.2.aarch64-unknown-freebsd-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "73ad5987b4fe7e9c2ef3afa247cdeda29cb82302"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "freebsd"

    [[MPItrampoline.download]]
    sha256 = "d5e64340f1839d7256bfaefb78e394631972b8790fe303919167fabb924e072d"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.2+0/MPItrampoline.v5.5.2.aarch64-unknown-freebsd-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "170bf3416611daf12ba63a2705801ce23b0490ae"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "de3b9842a0d6f08a14fe1862f7bc1b71dd6c116f97a1348e62d0bd85696cff93"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.2+0/MPItrampoline.v5.5.2.armv6l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0cb7d780b1eecae59ac785a456d0c7b0325f933c"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "107eeea53921ad73140c618c4e42154569849c36fbc863ec6948e84f4b6c9e5d"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.2+0/MPItrampoline.v5.5.2.armv6l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5934c692ffc21b73809a34d1c38b584df30fee17"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "fecb228ef2937e0782795803e317cbdea7163c897861fc33b0453362bc690f7b"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.2+0/MPItrampoline.v5.5.2.armv6l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b9e8fe8e5a9c2161622a01c836640080187af3dd"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "559a7f7464f48c2a729a804aa4cf966508b977aa5e9247730c91e0d1a805ee2a"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.2+0/MPItrampoline.v5.5.2.armv7l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "36102a71016dedc790b1aaeb4c473586f0f894e7"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "45e75ae2abb5f1471d1f4e1993d8087f31773ce03dec314d19f4e91c115f2153"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.2+0/MPItrampoline.v5.5.2.armv7l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5bfbe5c4c5edbf8451e1b112a7880e37cdb89ba8"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "1d1ead1e0272722b658125e254b3c24787c82bb148c14c20a90c250ee252ac37"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.2+0/MPItrampoline.v5.5.2.armv7l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "29c6e8efe39ca27522f3ed70d5c9dae0a75b70f8"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "277b8ed5981b1e77e14e3a2aa2d83a076c968b305448da4dac596d523ff30760"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.2+0/MPItrampoline.v5.5.2.i686-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "ef6ad38ab3875b98093da2970d896e164f2d9f2a"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "f114383aa677c806fd75a1dd14819132d59e62ab62f3d48f00c155a89ef16142"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.2+0/MPItrampoline.v5.5.2.i686-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "3276f0c28a32cb0007c4935b19b19cf52fa3d69f"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "9f9fe56f0b5dbe2b381ecc87556ff74526e848b70e440fed4cf85cba96753daf"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.2+0/MPItrampoline.v5.5.2.i686-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "c28800057a3bfa8adbdf3735ca1b8e7bcd4fdde8"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "c99695429de856a763215185e6ef4828d9e4519b501e870c210b46798d1c8590"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.2+0/MPItrampoline.v5.5.2.powerpc64le-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "5c937fb5163a37d5d6fb1330c7b9730c17e8a9c3"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "0f8e95083d5db4c44565b605d88f6549a892900745faf1c22d62b38290686b51"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.2+0/MPItrampoline.v5.5.2.powerpc64le-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "71f8145fc7ead6b7287dd8050eb84fe39036371a"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "b8e9b23f9a844e88f04a69f86823943aae836c999f238377a31c521b23a4b209"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.2+0/MPItrampoline.v5.5.2.powerpc64le-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "riscv64"
git-tree-sha1 = "df7b79dbae6fcb5ce267825e5e16df9d25243a9f"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "36d66f270948012ac15397f22984e1af514797d9e38b8908fd6729758bc2b569"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.2+0/MPItrampoline.v5.5.2.riscv64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "98468a1c2f7e437bef55eb44be9616d46180c49c"
lazy = true
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "dd74caa576470b952453a6cbff0d4fe2ae5172b0bd24577d758db7d929a5182b"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.2+0/MPItrampoline.v5.5.2.x86_64-apple-darwin-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "7205a7dee99dd2a71de48655776ca55ed72e93b4"
lazy = true
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "3ca68a878212e67a1c11fda4e4ed54fe953869a80db2ee1fb229dd8b54e42525"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.2+0/MPItrampoline.v5.5.2.x86_64-apple-darwin-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "8daf736dc91f634542909a65fd97286986afa2c7"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "43ec15218d1ece0781108464375df279af6a52a8454dfded4f09a6fb656df6e6"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.2+0/MPItrampoline.v5.5.2.x86_64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "014a2a2075dece75265cd14014c99bc243dd4d17"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "8a335f7e1e7eeedb75b454520dba1cde1ec1c6b32ddbc8c35ad7da766442330d"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.2+0/MPItrampoline.v5.5.2.x86_64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "29d21814f29d503b51314891a9e2cb4079778bbf"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "045826ee574ef12bc32685c9ca1b755f624ef30595523bbd435770da410f722a"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.2+0/MPItrampoline.v5.5.2.x86_64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "b0621f278163a1b9973d9fc70ac0eec360e8af1e"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "5fbcb88af5484ea130a2d8fb0a446dc1c2b39b3b640ce52dbcde7547c3e97ba5"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.2+0/MPItrampoline.v5.5.2.x86_64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "feaf1d038d89be942643262252ccd7fabd1a5bad"
lazy = true
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "freebsd"

    [[MPItrampoline.download]]
    sha256 = "ebf1e2369e4bbb2290ab48bceb6ec6e51151637827d01b04f0baa2330322323a"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.2+0/MPItrampoline.v5.5.2.x86_64-unknown-freebsd-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "b6e3fd1756c70632b37d6d43963fa294901b7079"
lazy = true
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "freebsd"

    [[MPItrampoline.download]]
    sha256 = "35acbc646ced7e22cc772bcc884871d6b971c72108c5861c8525e65259189e44"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.2+0/MPItrampoline.v5.5.2.x86_64-unknown-freebsd-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "a47565c272d257ab5a473a35e0f9b94f70717cb3"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "freebsd"

    [[MPItrampoline.download]]
    sha256 = "55b97b302b3190b9c49526ba8702245bc63178dd96b7c3ab1a70746129be9d19"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.5.2+0/MPItrampoline.v5.5.2.x86_64-unknown-freebsd-libgfortran5-mpi+mpitrampoline.tar.gz"
