[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "5a8ae74bab95a6bb656df18d511b9a9236d09b80"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "6f08823330c8eb08d7b44e8477b37bd9c5aaa5484dfe3dc261bbd2d144d994cb"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+0/MPItrampoline.v2.0.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "cb4596d0f49c9cc9a4d63021bf0f7b26882e2c22"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "ff0b64116994da758e47acaaf2372409dc72f1881c46785ad2cb5edfb0f91a88"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+0/MPItrampoline.v2.0.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6d8b18fb325f856b5acf3492f9f3f2fc4b603eed"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "df04542b419dc0a2c65ad1daaeabffffaaa83a3cdc4f22d28779726b9a6c49f3"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+0/MPItrampoline.v2.0.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f4a36516234afe390168b73c13f0c5ed7abdacf2"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "395de425053bae4ec51c9762bad6aa3de8d0c045055c3225120f78631e2cf9dc"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+0/MPItrampoline.v2.0.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d8c601ce9ed32fbe849f7a5d023d97bbfd3482af"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "53416f53584ccf81a3b3502ba3d0f8204afc6beccca4e74bf41981664075c462"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+0/MPItrampoline.v2.0.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "62bca1d161451c7a00cd2a696fb9b51b214b0e20"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "a8bb1227bf0d69420465262d9e2a4181a9da392a01ead4b880a71ffd72122f4c"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+0/MPItrampoline.v2.0.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "17b6007edf1353c3e6f5fbcbfdc7672b5845d8dc"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "1a22d9166c71d196ea8a5118d64f490cac5ddf52d06fdd306597460dcd604b61"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+0/MPItrampoline.v2.0.0.i686-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "6f806c749b56c0ac71f9778dca7cfe10eb46f3ca"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "faabaf0131e51ba0a1348b75538ca38d4cf7db16d3fed8089f1f022e3584b3e4"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+0/MPItrampoline.v2.0.0.i686-linux-gnu-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "9f703f523196d258a54618d80399704bc0904bf8"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "42c9221042a422515d7ff939ced8ca12d5b4b63f79cfb58c41569145ed660bd4"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+0/MPItrampoline.v2.0.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "9df89734423b7b75031f28814efcca1a4720832e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "39b41802ab000491d7b6234dfc45a1e01d0d34604efe9b073edaf7c625083539"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+0/MPItrampoline.v2.0.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "8d4c78cfcbab1e51cf71fa1ab9e9e6fb75078ade"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "871db601a138d1721c64bcac67f9ff5d95f802aefea1b117e53b116eb65d3ea5"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+0/MPItrampoline.v2.0.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "f7c040c0ff70d78930d270d0e197851c6074507d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "9b0a1027308d63d841c4c499a1fbe237a58bf1a15e1f9842f0a8287a6be6fde7"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+0/MPItrampoline.v2.0.0.x86_64-linux-gnu-libgfortran5.tar.gz"
