[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "a7a1673c6ef8acb234c9183a1f5b2c499d74d133"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "69a1e022e69511d95ef197c4036b7d6a70f952892940af9a16e1900ef0fe0843"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+0/MPItrampoline.v5.3.0.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "50e3fddaf95f504cf272ef5017a40919e673eb44"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "e748a0cc6d0c29178dde4323ce0df533245b25e45e09b1cd112134c908e9d22b"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+0/MPItrampoline.v5.3.0.aarch64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "38fa84d50fd9dfa11803a6ed24c7cfdf54a51623"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "2cb8735d53affc2754ad46b6c2893f0bc25389695c2ee46cfaab4295538ffc9c"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+0/MPItrampoline.v5.3.0.aarch64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "0fdc0c6d405820693c2944fd53ccfae178a4ba35"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "6c0aaf5c9431c6640201f544ea45012ffaf4291534905cb62b28f2cac7423e21"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+0/MPItrampoline.v5.3.0.aarch64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5ff5c2820fa9b7c6f6251ddf16bda83cd7e896c4"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "6e8d6b14cb18f30ddf37cdac2b481cb1e6beded230f9a31d239a148a932c0ec2"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+0/MPItrampoline.v5.3.0.armv6l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dbf0d329f5275ecca2ead249776077da3ce3f051"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "6d6f1fdd5d80efe2fb62182e98d1389e8084305c808c073ea1e5408e9f7f8ca0"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+0/MPItrampoline.v5.3.0.armv6l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d5199e95e268d294df29294a71266ce0b31e70d6"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "92dc7e2e2945331aed0682a032133bd96bdd1b1a02da35e244eafc0c2ab028f1"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+0/MPItrampoline.v5.3.0.armv6l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "973b2ffdddd91183eb7539a17e37f14a86f0eda4"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "074432500b01963498284dfe9a20c3856d7cff93a071d6de10dfe187eb2e807e"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+0/MPItrampoline.v5.3.0.armv7l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e05761213ff099db4649a47570f6d15f7b317e9c"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "c585d9d0eabfec37fa227aeab79c83bbc7adbcc03e6080a8990432d2ee88a109"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+0/MPItrampoline.v5.3.0.armv7l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d63beebfef54a4c9a54270c85e2d301ced1a57e5"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "dfe9aeb2191d125eceb0aadbcd8a2b5bb215070afd5fa966b5e0491e44a0e154"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+0/MPItrampoline.v5.3.0.armv7l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "0bf118bca7953cf2379708e0539c9d1766401a26"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "b5070841aa337aa468c84da09f0ab7d22ab90f83fda74b5f8927b4e33cf66809"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+0/MPItrampoline.v5.3.0.i686-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "2ef80918f4176356d3e8e25d4bcfeedcc3569653"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "06fb62ac5bb147dea5ee1561b8335d19d1a798b2e0c95e111eab94505293dedf"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+0/MPItrampoline.v5.3.0.i686-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "944851f7b370c5eb85b1fe7b63a476c52b28aff8"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "1a49e8690e29f754d93449668828300a799bdc718ec970af2679a1bc6e0802e2"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+0/MPItrampoline.v5.3.0.i686-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "97592bdb07256d72f6f8a6f68cbf255a37e2bedd"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "0e708d59191effb80e031b27c08aad05b45f1c174b1768ca298238d5eee6ae4b"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+0/MPItrampoline.v5.3.0.powerpc64le-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "2843c121e26676f9826cd886f2e984f7d49426a9"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "466576d5dee0f4b4a3916e7a291ed8dbe9bdac5f69f3dd1388a43a5cbc2d4050"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+0/MPItrampoline.v5.3.0.powerpc64le-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "adf701acfc45ce3def78786baeb1f745febff843"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "d863babad410a90e554d161a74c38d925d16884e959d93a1149abd7b304d68ae"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+0/MPItrampoline.v5.3.0.powerpc64le-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "a6dfe829d3bfc4ea3864842c10efe1bcdae12f4d"
lazy = true
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "608f381985c24cbf1a31adb32033fb5bab5489b5122fb1c73eed9677f29b0bf5"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+0/MPItrampoline.v5.3.0.x86_64-apple-darwin-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "e1763ff110a54c7f1496a06e20bd4b2abd17c7a6"
lazy = true
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "8b4fcdb62c653b3d4a6ac77aca25105bac015e92807d00affd68fcad975f6b5b"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+0/MPItrampoline.v5.3.0.x86_64-apple-darwin-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "90ad476ac9ad8de9378011687cdf28763966882d"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "1ff209cb6efbb1997bb674d89083378f628dc535e3aa205893c5058cbbb49ddb"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+0/MPItrampoline.v5.3.0.x86_64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "6125d3b7df9a72bec732ed755b6c77525f1d1a61"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "ba81a30b9f09caa597481b7496c10acd524567311213881f53eec381872db377"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+0/MPItrampoline.v5.3.0.x86_64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "bddc51442fd958f8f0844e33432352b815886147"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "c3f6012658f7851e5083ff4bd1a47a4c76e082afbd134c093d79b082ef014838"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+0/MPItrampoline.v5.3.0.x86_64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "1ea95674bf5dfb1cf171c92541289230f9ed32ee"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "98475bca293dfabd12775389d2275702a2c1f556c24f3a6e25dc94aa03ccf589"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.3.0+0/MPItrampoline.v5.3.0.x86_64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
