[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "b631ed6c4947c91b2ed255b3c79c0f813ef5e88d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "5880d7c0fc89934fac4b19b4a168493b8b30e66ecde53b4dc3ed0fd32bc302de"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+0/MPItrampoline.v2.0.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "634c6a2458bb7100e4626b57e22a164d1de6ffaa"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "e1729adfa26c57a3fa8e536c3e5ad08e4c3446b6787a8190497f004443aeef37"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+0/MPItrampoline.v2.0.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8200aac4e6fcfab66b5ad106519dc671c5bcba27"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "9569f33a75e6dc1b4a67b9492ffbe343c5e1a817514355e9a21d99fd52b9edf0"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+0/MPItrampoline.v2.0.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bb997fa68074936a14d4c635804ca2600b306737"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "8a62b3ab6a4d1fee151c8a898a4bad807db287991dd810ae7ea6df118d56e191"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+0/MPItrampoline.v2.0.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "5653a1a42a8865bfcbab5e42c1af3f878fd95eeb"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "0ac1011eb5dad8102d3550e7e6fa31dbd1425c7e3553cd79aa87d10a8cdaa475"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+0/MPItrampoline.v2.0.0.i686-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "1b8803e160982b683f5efb4469a2b80115768f03"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "8aec21be76859dbba989e52689403986f593f00231958004872ed152d207a044"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+0/MPItrampoline.v2.0.0.i686-linux-gnu-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "7d49b5a0440a07ab02d273f8b877c5e34ff08468"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "b9da7686f3ef0b2c4073476c352b0f53ca8c1a6965cdc81f8bf26639bfdbc40b"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+0/MPItrampoline.v2.0.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "0ea5911203f13e188825a52a8d8b43f891f2a9f6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "130ed61ade490f81473a93d82df05eb871ec49ba033564b796353a6273066173"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+0/MPItrampoline.v2.0.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "40231a4e00d357cf181b408f716c34292a6ac855"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "8879bbac7795aa148023db30f39e553f28c41990cc602b319f7acbb755642a63"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+0/MPItrampoline.v2.0.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "7708aa28ba018c6b709649ded34e7ba228321e2d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "a026f6941746f4b7f533181f0c89806c9255667339433df98fd9fcb3bd8f126e"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+0/MPItrampoline.v2.0.0.x86_64-linux-gnu-libgfortran5.tar.gz"
