[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "485badc59aee3598c26be8443f3f50f718e216c7"
libgfortran_version = "5.0.0"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "435f4ccda0e08f37cdd5ab9f4f1d9659df0a06758e9bf33c9cfb524088f4d6e6"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+1/MPItrampoline.v2.8.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "15d06a9e178f0aa34b7474d013bf2517e6a14e56"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "487fb0c3852cb42c5a05024dc0fc88273f0eb0470545e9858d5644f2d6539554"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+1/MPItrampoline.v2.8.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "bae5694ac9594cdbcb115ff864c751f541856535"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "8adcb4d5eb2197ee2bfab5734b8153b370734f6159569428040a1cf041a79dad"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+1/MPItrampoline.v2.8.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4495208700bd2815d2367fa1b3cba9d7fca6c6d8"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "7dc050b33b1667bbfe7607affe82bf5cdfb6e3fd6e1c985558f977f8debc403f"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+1/MPItrampoline.v2.8.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5af83218eff504a0937a97a9becd474a18e11f24"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "9b1c174d018e8338adc5295dee6703631d4fe6d97c7543db2ae156b6b6f68651"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+1/MPItrampoline.v2.8.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fe6236512ea29573b817f0b414b93c06883225ce"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "e3c9d4861449c6d6cd6bcdd7116a3d12d8492288d2f9b54e981c7d9d8b17c36b"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+1/MPItrampoline.v2.8.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "68e589fd9fdd1b51faaf16118211101abf4b897e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "387b434db13ddc20595c9c2de6c5f2aad940808b115f7d38ec17ae98e9c2ae17"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+1/MPItrampoline.v2.8.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "e0df183cb5559f65b941c4f33e5cbfb9f960385f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "75c3056ead7afcfe239c0967caa948431d41b856979bfbcfa5ca76257af38746"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+1/MPItrampoline.v2.8.0.i686-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "6f8f12932f73a5f3320e767671fe07e7b043bf0f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "d5e411d3d1ad757d5c9c3a04c3f50876ccab234d4c6ebbf39b32ef7b1d16f363"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+1/MPItrampoline.v2.8.0.i686-linux-gnu-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "159143f4b017bdc0d6d43e87739cf3618b2be816"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "aed9291c3d9f2ce389bc24f5d5218876ce84f969c42b7cc8245049673a35453d"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+1/MPItrampoline.v2.8.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "fe1c2a8dd2fc57926db92aa2d4cde7be9a209da6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "94e4f26ab25d7a5e9fc915fa60a00913e7ac27c436b1a2908276d7c979787d7a"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+1/MPItrampoline.v2.8.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "2480512d2930997fb83be1f8ac67fdfb29749c79"
libgfortran_version = "4.0.0"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "539920d85b1e098dcebee36839a8e10a9b0cb478c6562cb14896fa070dd20738"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+1/MPItrampoline.v2.8.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "c225ad96b093cc21aa9b01c97a965c8b0f8a34b3"
libgfortran_version = "5.0.0"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "8d2fcb07ca89a9610376b2f85bb6e9f96770a4a087d2c8fb6a8af555d6e1c76f"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+1/MPItrampoline.v2.8.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "f31611d34db83aef657b6af13415a8fec5956846"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "4dadecfceb3a8e0eeaea29e7645e4a6178589464bd310b72dd21297e6cff5110"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+1/MPItrampoline.v2.8.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "0268c3f3f489280557d6116ddbdfa1193ed5416b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "ff77fa258d93f133673b6abdbb6cbcbff83439d4c54e42386114a10b12973e7a"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.8.0+1/MPItrampoline.v2.8.0.x86_64-linux-gnu-libgfortran5.tar.gz"
