[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "aab1e2fd3f3d39b675be5c27e50a0066d3db347a"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "76cef2b906fce6addb763c2219a3d74dc1fde16b6f2bf59337c435032c2e7d07"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.0+0/MPItrampoline.v5.0.0.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "4f7435a32102976760d5f1070531afeb5d204249"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "cd14e2b6a5fca31969c270cb141dbb116fd364757bbaef115d646e0776a033c3"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.0+0/MPItrampoline.v5.0.0.aarch64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "3820398b0b6ab13b1fcb41bfbb63c9a841111a79"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "63437826553dbe1406a40f4f7cde0a99ce9077efc04b1c47c783a1127a66be5c"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.0+0/MPItrampoline.v5.0.0.aarch64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "15ed847618abe1530ac3836d1bdffd9092f8bee8"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "de37352fc195c44e78cf0d0f84bb270fc67b22bec9aa9b2c245e4ce96c2f6858"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.0+0/MPItrampoline.v5.0.0.aarch64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4f716e60e6318c92338b7ec49700ed23bd9254d4"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "fa49989f568d46193e7f36b05fb890621e4c8e91234eabc4d0d21becf2dc8b2c"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.0+0/MPItrampoline.v5.0.0.armv6l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2d6b8f34e37c9bf619e004f8a25c36709c1ef199"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "1df346f839e71d4c9f32b60a4802fcb3604e8e14f453fcb282c3b1e5c89b8f66"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.0+0/MPItrampoline.v5.0.0.armv6l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "39d61be1a656c24e3e13525433b6f3f357e0f549"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "4f82b445d56032f5ab9191334f5c67ceda498b8a842b824d2cfb644fbfb99741"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.0+0/MPItrampoline.v5.0.0.armv6l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8670a0c67a2a327a046da322d32758509333834a"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "8301fcec1ae72a8f6f4773aa8e93c6a848df6a20fa931bd8df92ce671678bc9d"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.0+0/MPItrampoline.v5.0.0.armv7l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cb05bc90fae3c65e3420b46ed41cd278ca1d42ca"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "c1597e40d9cc93527509bdba8c612eca67cfdc55bae5d2f4967103e7a8c97530"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.0+0/MPItrampoline.v5.0.0.armv7l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "09b49ce563710bc809edeba781961d2f876f466f"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "ab0021bb3e732d57e1af86505882b0698d40d2f0a610f9f90fd1ca535c9121c7"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.0+0/MPItrampoline.v5.0.0.armv7l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "8b09e8c2d650457cb5540ed3c07a99b288404e2a"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "e19ae9475efd83e0432348d9be3376a68b4f2b55b773f5192f89a18facb5f203"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.0+0/MPItrampoline.v5.0.0.i686-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "f1915941ce4ba33c1505107fa2d5e8a56e6c9a91"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "0c6706106be3492c303eec458c614dae4c16f9f4a4f5daac044365cd81a39e2a"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.0+0/MPItrampoline.v5.0.0.i686-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "ba4bdf0b73a3b89ef4fd127967c13cbcdf6cbad3"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "29252946fef28f0f72257dc5c6d3347f6271e6305dc7836af7ade6a0a58d7b8d"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.0+0/MPItrampoline.v5.0.0.i686-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "f141dfe6dcc2508d53338b7d7120ea7ea602598a"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "fab85eff2bd215f21026003db7aa5b502da11caa47ac03d9211eafffa7c79505"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.0+0/MPItrampoline.v5.0.0.powerpc64le-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "9adb55c79eb3351a8b2a23222901d2c4c777eeeb"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "141036906ad8e797fe006d7378e004d745bf8dc5b71b3f54d2a682495f268146"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.0+0/MPItrampoline.v5.0.0.powerpc64le-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "bde5133f3a6917b7761a3e8b39fccc673656ab50"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "2020a497fccdbe599161d9e1951146d835669aa2d97c76db57eb4b393f3c8d17"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.0+0/MPItrampoline.v5.0.0.powerpc64le-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "6880f9dba2d3d8d26461dcf06e6c39ddc4fea494"
lazy = true
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "c60fde1b162f3e1456c7300a3e5f7a5bf2f5c76353dc276ed727dbc3ae3c585b"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.0+0/MPItrampoline.v5.0.0.x86_64-apple-darwin-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "380ea068fe6bf282851044906cb09c1a7e635140"
lazy = true
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "fd0593dc4feb56f53b9d41aaafa1097c5f41bb02870318e275d1de00eae155e8"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.0+0/MPItrampoline.v5.0.0.x86_64-apple-darwin-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "5f5fdbb0a9ccdbc022750d72af2361b783eea0de"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "0bf2c04bfed75833e6e2a9a81511e806409ff54190f5ca05aebad29108976a04"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.0+0/MPItrampoline.v5.0.0.x86_64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "3f88141d30a764f6a4ae7ad3b275248490f8743d"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "cef613b28afc641268006e4e2220f24636ca1748d5b78dd9febe9ba2403d8ae3"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.0+0/MPItrampoline.v5.0.0.x86_64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "e548489064b5de1d75a086aa70258314e942e4d6"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "e198908b8f3df4e3682fb73cd31bb7306397f51058b92615fae1b868d2ca8dbe"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.0+0/MPItrampoline.v5.0.0.x86_64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "da1e1bdf626233bd706317c328c1ede005625d68"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "bfe946a75a2e276377ce2bfdf6cfc362185e96b3ee8175e15c2d415f9fea8327"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.0.0+0/MPItrampoline.v5.0.0.x86_64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
