[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "1393631f867e8b285a80a2d720a49f700e8f6860"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "6d601fa8025aac539d81f8fd16bf22df5cf1c3de503d6d071dde8d5bdf2e6787"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+2/MPItrampoline.v4.0.2.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "4633fe9c916e3c7c807072eceefba76cdbef7b36"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "0465681bd547dda2ab70511cb40cc0481699d55d05e00bb41b87af0cf10abe2e"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+2/MPItrampoline.v4.0.2.aarch64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "bfd429196abd74ef716227cba588f7e89344ba50"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "f07bb903151850f41e722e7f07d09671d5bcb916db79ec4e7a66942637532ccd"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+2/MPItrampoline.v4.0.2.aarch64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dfe003d53eea8a8bd911312c379bad1ba996f588"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "f25862452d99302da90d9bcb4c76255bfe1b87d1c7f4c1607a2d3aba64c9ae3f"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+2/MPItrampoline.v4.0.2.armv6l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "10b479ab120be2112cd6a995f1a84ec38e6ae2f4"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "83a2597a9cbe00252fbbf3ffac473bfab99f49debff69d3f8d5883b955902d8e"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+2/MPItrampoline.v4.0.2.armv6l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fd01ebc498ecc6afb29ff26978b15ea3caba4684"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "a6a6aa5aaa263d6cbd12624c916afa503bfa35e39ba974ef5f2b1b10ef7bc84a"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+2/MPItrampoline.v4.0.2.armv7l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "915089034c70cb30178fdb6d15f3e4e71f072ff3"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "ed97a1fa261236ed43525d132dc7104491cfb028245e1701dd23b8eed9b6dca6"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+2/MPItrampoline.v4.0.2.armv7l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "3f260a40e151bb8872f81bf9135181107cda1909"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "6d8510c309819261414cd82d09d869d9cedd7f0cc3aaab5344cbd8124dd96376"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+2/MPItrampoline.v4.0.2.i686-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "8b6c7467e85875bcb8a7c3dd97ab59b023b31080"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "c221f42f66fce3975696ce498a111808c5fa0b07e32bf2f9bfb0f18e99b15364"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+2/MPItrampoline.v4.0.2.i686-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "8053176cb17b6165c08c2ee6052686a22b2551c7"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "f86e6609b19327b2f5bae01f404bc732b51109564b5772eb00f2ccb111a12a80"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+2/MPItrampoline.v4.0.2.powerpc64le-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "3d1edc6c158aaa22bbb8b63f3cb909720ca78300"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "b6210ae5ddb2484bf6e55848e9e132087d4cb73b61f821c25f24877c1c4948d5"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+2/MPItrampoline.v4.0.2.powerpc64le-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "c27bf72c781585ece89d68ab0d7d0da12c134199"
lazy = true
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "7c9da5f69a46f8bb9d0d63b10ee129a125e4339f2bdca1dfbd7d9514e339a23d"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+2/MPItrampoline.v4.0.2.x86_64-apple-darwin-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "f4e79efd4a94ae562f2c5423483a0bc40c412ad7"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "64181e53ef0f0e8ec885b1623bb0ba63e54b03b52ef728fbfc800c5e56443ca5"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+2/MPItrampoline.v4.0.2.x86_64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "a084b1e648b0c3bc3a39b0069c5326ea8f538a43"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "f75495c7e374a8a51d803a7dc654ab060a022a9ac49490471c55742d7caa063e"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+2/MPItrampoline.v4.0.2.x86_64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "a0b26eb576f84baea5aaecff1ef3d4461a239131"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "1372e8d60e425b0f0e6da1e5efba8c3f45b69fd169c83558356e0bb828bfe26c"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v4.0.2+2/MPItrampoline.v4.0.2.x86_64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
