[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "af2a18fea2b8ccf7fd74a60d089dffc2f2211194"
libgfortran_version = "5.0.0"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "c1d7415122c2c0e4671019ddd9dfd50cffab7b4924d0ebbb008f5132bfcefa58"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v3.3.1+0/MPItrampoline.v3.3.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "7e34e0a07ff3665624e5ac12928c24b9ccc0f096"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "b0ea41d5cab253513c1fe280a1fd5fbba0ec93eaae22dde9a538561773fd16c8"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v3.3.1+0/MPItrampoline.v3.3.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "a7fb0178a7aa5a1bba6c1d9ccd2d7783dc8873cf"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "70d8d7c159b7d074ca665f2393e92c6b114957c45787623b61defd4775dbe1f5"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v3.3.1+0/MPItrampoline.v3.3.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "79aea78c08817292d46d7e6b8744da599c65052b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "dc318a250501ab3b029769f6f8d40f0e3e560ca24411d8ad755f88b44930c01d"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v3.3.1+0/MPItrampoline.v3.3.1.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0c37db86fef9afd94d9cdbcd393e31c3538a43e4"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "a6301c57708ec4971727404921cd527d0864c726ea2418c1ed1b3bbe08ae6f62"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v3.3.1+0/MPItrampoline.v3.3.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "34ae1bc5c84d07f8e1a4572de66010e698ba3278"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "b533f1e8bc194a82fe3d415d836e7011de8b901fe249a1bfae5ad779f2ff9e3d"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v3.3.1+0/MPItrampoline.v3.3.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e294949266f70e075f56522e7ed787387bb612f7"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "8541fce4a2072ed34d8682b0f064773862c1dd9ae87aad791d90e8d9a4ed3e2d"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v3.3.1+0/MPItrampoline.v3.3.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "072f200515a78addafe8bbfc1700e6fa6ef91295"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "0397e432199a5e1fe53ead30c56f2185992df613872437330cc8a5afa8221352"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v3.3.1+0/MPItrampoline.v3.3.1.i686-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "ac9ec3923d64751d06760a5adce5b6cd4d0469d9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "76f03339bdccfad3f0b78d98e133d55083c2604fb550390083d0bbfff717d588"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v3.3.1+0/MPItrampoline.v3.3.1.i686-linux-gnu-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "a4f95d651c1231365c267dfd7235162b72d631db"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "e777f8f5b58de6a13da946e969ed9513793ea2f4a8d394706ba2e05c0691eed4"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v3.3.1+0/MPItrampoline.v3.3.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "884e1d6fa6496796be477520b83ad0ae9f490351"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "8012920ee11e994232f890bfd8d5cc2a41146bdb9a31962b57ef30d60a091bb3"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v3.3.1+0/MPItrampoline.v3.3.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "2eac9619aa6fbf645ea79a6f89490095653c2da2"
libgfortran_version = "4.0.0"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "8c8314a61490a16be6b2555a4e82b04363143cb40211e40f3423489502a09d0d"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v3.3.1+0/MPItrampoline.v3.3.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "10b25d5a15959f01780a982d6d76d5f81de207be"
libgfortran_version = "5.0.0"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "68646d3f6d99d35fd0bc5c5953a90f7c8422a989a04d0753c0bbb682cd10891a"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v3.3.1+0/MPItrampoline.v3.3.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "dcfb1c5cfbd07741b7b740f85eb0daf605413757"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "31daec45c3866a69fd452e40f7abf09044c65f38db4b75f002e62975d0ce7b0c"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v3.3.1+0/MPItrampoline.v3.3.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "0b421a7738b8ce6f4afbc6aea0736f07db5aad15"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "97df0b2f5f36603ba9af9ba727dedf8ffff4a0a8aa8976df2ce1e6061108d0d6"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v3.3.1+0/MPItrampoline.v3.3.1.x86_64-linux-gnu-libgfortran5.tar.gz"
