[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "849bd928f8b667a13506e6fd706c3c27fb401943"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "9aeda14e2487bdf98dbdd88c3a485159a0e64dd74e400272e05ec9f0046ceecc"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+3/MPItrampoline.v5.2.1.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "bbd90746386d6cfb526e67715144089f00a6f852"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "9fbe7936e356cf909f8eb3e89eb369f1c17fe07e7b1046a99843ded74194fb22"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+3/MPItrampoline.v5.2.1.aarch64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "a0aa0af7c1141c9870b7168fe83290bc1ebbb4d7"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "64729b07019851c65c7648456d6c2e2770ad25523aa1ca4e1b468afef73db37e"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+3/MPItrampoline.v5.2.1.aarch64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "aaf069fb1bae7f8b9d02a5375cb9e648d52cbe43"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "3e15bd0866bb289e227e6d31c86c7c375f93023338611d6beaa7344d961ddafb"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+3/MPItrampoline.v5.2.1.aarch64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "90257bd4f2202d9cb823aebdfe02f6bb0f171768"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "7291699d5543360f74480a59d96a97b6dae31f1c2e43d7bd3861907b22ef6977"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+3/MPItrampoline.v5.2.1.armv6l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "32498ef22705e4fdffc1dd3fcbc204d874a16caf"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "ffc9739a13f7a8c35a71d8b0d03d1fcba0ffefa3604a60364ffe5af8a52e6b15"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+3/MPItrampoline.v5.2.1.armv6l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1b645f7185877b61021f910f23bd94faf5de7b40"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "822a6a0ad541f8884e6544795b82cc198fcfb75f015f7564779a335ff9a0775b"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+3/MPItrampoline.v5.2.1.armv6l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6dabdeea168d904cc26d414101fd37d0798c4c59"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "9a623adae10d6e466b3f10f92acae73d454215fe720162d08fdd268eeead21e1"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+3/MPItrampoline.v5.2.1.armv7l-linux-gnueabihf-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bc974cf95069b354e17035370c70f94a71bfdf1b"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "05b5817d2494b52d792ec80b1607038cfce9b628f7b9b16ef12eff7a1463ac21"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+3/MPItrampoline.v5.2.1.armv7l-linux-gnueabihf-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3311a5cf5d12d2ae18f73b2b605a6258c66b0b0b"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "bf7b3c1d57f14c623609cbb11ae57e7e7c553e15df2237f2a93d0d6fc0d21963"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+3/MPItrampoline.v5.2.1.armv7l-linux-gnueabihf-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "5a76251de65ff3e4a59046fd83b26b53e28157f2"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "3cfb064e12aa1df79f40149d786b3b63eb52a16480cb16727d515bba662a3601"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+3/MPItrampoline.v5.2.1.i686-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "a2b1e2ef141319e6b369be1c319f9a8377dfd4e6"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "4e42774a094199cd7259628ad0638edbc1800b6b2ee194355a29d8731f11b1c8"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+3/MPItrampoline.v5.2.1.i686-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "7d2e9b315aeaad0e745b8265a880b11e3c8645fe"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "4a2b2d6722617287ddcfa28b326e165fe46b15f3060ff71feb25107bf63fb1c1"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+3/MPItrampoline.v5.2.1.i686-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "59ff2a1cd61dc2fc63fe736f6788ba3fda7aab98"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "598bd15d63df71d33f6e0a13dfbfcccfdb558eee667b61f4cdb7f360f33cf3c5"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+3/MPItrampoline.v5.2.1.powerpc64le-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "947067cc97cf924a59527c6a1660b38e2a10b5f0"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "fa3836bc268887582de13d13c3a4a6936525fccecf11718462351dbb3aacd39c"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+3/MPItrampoline.v5.2.1.powerpc64le-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "93689319831d57019bd0143fbb4bb6fc67a91684"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "d77c3ebdcc2cba71f401615d126a5223089c008a476268b511618d7df4dee2ac"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+3/MPItrampoline.v5.2.1.powerpc64le-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "d6e0ecf215e51c8dc58c4abca91e7dd11f75e424"
lazy = true
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "5229e14ecf4dcd0dcd880d2705a3b4d40d7b92271144ca23ec8bc54ed98ce5db"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+3/MPItrampoline.v5.2.1.x86_64-apple-darwin-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "e54d227f244e5843d1677a763c95d987e945fbe4"
lazy = true
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "cc57d59aaba2cdc3267f434073ff71c3014418af118f3fbca1a29be897a5044a"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+3/MPItrampoline.v5.2.1.x86_64-apple-darwin-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "3ebb2bf754952bf2ef96ec4a490bfbd75ac08f5a"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "06f4f11b4e50d95dc179abb1fa7b2b93df9edcecdeaab7a88a82152106c9f45b"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+3/MPItrampoline.v5.2.1.x86_64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "206e18b74f2384d610456c6801bcc15011b27b1e"
lazy = true
libc = "glibc"
libgfortran_version = "3.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "0a989b5741b6395029e81d41db1afd552b63ed828a83f05e5bcb0174052dba02"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+3/MPItrampoline.v5.2.1.x86_64-linux-gnu-libgfortran3-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "1ce6bd32bc869b2483bf50f0168f5062801213bc"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "b83aff9770ff35d010eadc0522e9be12ab8bcdf249b8c17d833f6454dcad82ff"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+3/MPItrampoline.v5.2.1.x86_64-linux-gnu-libgfortran4-mpi+mpitrampoline.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "c29315f424e12dba009e1ce17b2a5b0f817a6f5e"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "af6db57652d4468b1b9fc544eb8c3849883f87e171517f6ee11e041f9520b461"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v5.2.1+3/MPItrampoline.v5.2.1.x86_64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
