[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "d5d03a79dfcbbdf357ac4805e070946a5cee153e"
libgfortran_version = "5.0.0"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "70c26dfbe7c517a6905b0fc6ef27569e7b6553c7802f283e31c3240589d4f816"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+1/MPItrampoline.v2.0.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "49b3d22b914cb4544ed48f9b1a4b49cf691a6ec6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "5e96a1145486854a142191e042c44047e9dab61e818244d8eef66142ffb30f31"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+1/MPItrampoline.v2.0.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "aarch64"
git-tree-sha1 = "50cf940bddcbb9d0c2647b2f9ba8df59543698dc"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "7b7aaf1a13230c7831cc0c334c2e38ea01dd2949e55bfe0acf0b52f6d0f661f4"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+1/MPItrampoline.v2.0.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4a0dd665b70837b9979b01f6eab779f75c225747"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "4cffc7125a4208b4c7726a31fba2234487b2f792e91b4ce116a673ff77bf0d07"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+1/MPItrampoline.v2.0.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f79ef2debe0bc474fd23fa4eee9510984f362b72"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "a9757a0b7d003cabcb857cb0cbb8bd07dc484d10253e24ca30b44ff342571440"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+1/MPItrampoline.v2.0.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "99cf3f57adac88da0ca74d00a6cdfcff34933b62"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "87e9665e75f94abe82aa2fb3e0c90647ccd6a7ee96f8731d0601df6d13a58fcb"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+1/MPItrampoline.v2.0.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d3dc7812ec4ad80e59c873c9a34ca7cdb5fc6176"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "7895d7a0268329faededdc72dcedcf26af310418c24ff304b5f0e9cec94e02b6"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+1/MPItrampoline.v2.0.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "3b09d3c5d88461d4176ebb00b44d8b107a348839"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "986f388e3a9a6fcef1533c97532e321b603a1a7ee1c86950e7e2be5548c88879"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+1/MPItrampoline.v2.0.0.i686-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "i686"
git-tree-sha1 = "906a9a761463826600034ab1eb178828e7c7465f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "2675f488703e2a96818f9c60fefd8285dc33a4e62b55a1e5c50fca0aaa1d7416"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+1/MPItrampoline.v2.0.0.i686-linux-gnu-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "47546a15f4c278d39188ab903f9f53d8ce6f0537"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "af660764deb0e2fbffa6ff320456c2b3ffb2817790ee53c0c3da67a6466c385a"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+1/MPItrampoline.v2.0.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "powerpc64le"
git-tree-sha1 = "cb13ce6088fe297df25f36c1f6bba9ac587f7ef3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "133ddf384388128c3f1e9d85cff53bd28b6c4f0b6ea3f40b3bffdce8d6bf167e"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+1/MPItrampoline.v2.0.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "4ac40a926f8a260aa03431e197b98b70ce03d2cf"
libgfortran_version = "4.0.0"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "a5de4ba0e64551b49f615436b249b56594eee10d57cc310d94abccbe6f651522"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+1/MPItrampoline.v2.0.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "324f51beea1763f447ed35ba02b7622bdbae8041"
libgfortran_version = "5.0.0"
os = "macos"

    [[MPItrampoline.download]]
    sha256 = "e10d5a3e10d5cfa76d2fbd8f8b119e21fd1ca0a6e158e8ef0251849b5f12e9aa"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+1/MPItrampoline.v2.0.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "26423c377ddf50995901bf4bf917fda9b02272ed"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "70b916742048e3f4c2d421b05390f67523bb4ef92d451bf6c3df2868a2530eaf"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+1/MPItrampoline.v2.0.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[MPItrampoline]]
arch = "x86_64"
git-tree-sha1 = "6dd4cc57e6f25da2932088d0d2121bb3dab3c7f6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[MPItrampoline.download]]
    sha256 = "cac3964610abb7072361fe0fb0ececdb09498504bc85aceefbf652089e0788a0"
    url = "https://github.com/JuliaBinaryWrappers/MPItrampoline_jll.jl/releases/download/MPItrampoline-v2.0.0+1/MPItrampoline.v2.0.0.x86_64-linux-gnu-libgfortran5.tar.gz"
